interactions:
- request:
    body: '{"messages":[{"role":"user","content":"Say hello"}],"model":"gpt-4o-mini","max_completion_tokens":100,"stream":false,"temperature":0.5}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '135'
      Content-Type:
      - application/json
      Host:
      - api.openai.com
      User-Agent:
      - pydantic-ai/1.83.0
      X-Stainless-Arch:
      - arm64
      X-Stainless-Async:
      - async:asyncio
      X-Stainless-Lang:
      - python
      X-Stainless-OS:
      - MacOS
      X-Stainless-Package-Version:
      - 2.32.0
      X-Stainless-Runtime:
      - CPython
      X-Stainless-Runtime-Version:
      - 3.14.3
      x-stainless-read-timeout:
      - '600'
      x-stainless-retry-count:
      - '0'
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: "{\n  \"id\": \"chatcmpl-DVJQwEgVkViekNXtfxvvq6hxe6jIg\",\n  \"object\":
        \"chat.completion\",\n  \"created\": 1776355242,\n  \"model\": \"gpt-4o-mini-2024-07-18\",\n
        \ \"choices\": [\n    {\n      \"index\": 0,\n      \"message\": {\n        \"role\":
        \"assistant\",\n        \"content\": \"Hello! How can I assist you today?\",\n
        \       \"refusal\": null,\n        \"annotations\": []\n      },\n      \"logprobs\":
        null,\n      \"finish_reason\": \"stop\"\n    }\n  ],\n  \"usage\": {\n    \"prompt_tokens\":
        9,\n    \"completion_tokens\": 9,\n    \"total_tokens\": 18,\n    \"prompt_tokens_details\":
        {\n      \"cached_tokens\": 0,\n      \"audio_tokens\": 0\n    },\n    \"completion_tokens_details\":
        {\n      \"reasoning_tokens\": 0,\n      \"audio_tokens\": 0,\n      \"accepted_prediction_tokens\":
        0,\n      \"rejected_prediction_tokens\": 0\n    }\n  },\n  \"service_tier\":
        \"default\",\n  \"system_fingerprint\": \"fp_fe7a5277a8\"\n}\n"
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 9ed46785c8e8dda9-YYZ
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Thu, 16 Apr 2026 16:00:42 GMT
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains; preload
      Transfer-Encoding:
      - chunked
      X-Content-Type-Options:
      - nosniff
      access-control-expose-headers:
      - X-Request-ID
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '839'
      openai-organization:
      - braintrust-data
      openai-processing-ms:
      - '589'
      openai-project:
      - proj_vsCSXafhhByzWOThMrJcZiw9
      openai-version:
      - '2020-10-01'
      set-cookie:
      - __cf_bm=pAKb.oUgkTbgzuWcjjy1dX1yGH0ZY59kKjYenRyiJuA-1776355241.8865688-1.0.1.1-zpCyhX2Qgr7bEQXfQAROWTz0.LQ_u2bXfJ8GBUrTG7kxZxIlL0zOy4yAbepfhYmnElwhc9tuvFAwQ_z9NXF6cx3Mag0NFJuMlTTNltETw93E0f67RHmJNTdK4sb_nJoY;
        HttpOnly; Secure; Path=/; Domain=api.openai.com; Expires=Thu, 16 Apr 2026
        16:30:42 GMT
      x-openai-proxy-wasm:
      - v0.1
      x-ratelimit-limit-requests:
      - '30000'
      x-ratelimit-limit-tokens:
      - '150000000'
      x-ratelimit-remaining-requests:
      - '29999'
      x-ratelimit-remaining-tokens:
      - '149999995'
      x-ratelimit-reset-requests:
      - 2ms
      x-ratelimit-reset-tokens:
      - 0s
      x-request-id:
      - req_e4db09dddc85424a9ae2df7b97158f52
    status:
      code: 200
      message: OK
version: 1
