# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 9daf27f19d9e0340304d7a3e7d0edb28380b94c6
# OpenAPI spec SHA-256: 5ec753c0263c0c44cd04f741edfc7e8bad491cc25a2113d029e84edc076520f0
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: cc2dbd2430abddbceff7f693feaffa844fa536663621674e67d06a78aca61f17

"""Generated private model types."""
