# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: d52050e09e8da2a95284c40fcad27478a4585f3124f824d0fea3b1cc10dd105c

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import AclObjectType, Permission

AclIdParam: TypeAlias = str
"""
Acl id
"""

AclListGroupId: TypeAlias = str
"""
Id of the group the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
"""

AclListOrgObjectId: TypeAlias = str
"""
The id of the object the ACL applies to
"""

AclListOrgObjectType: TypeAlias = Literal[
    "organization",
    "project",
    "experiment",
    "dataset",
    "prompt",
    "prompt_session",
    "group",
    "role",
    "org_member",
    "project_log",
    "org_project",
    "org_audit_logs",
    "project_group",
    "ai_secret",
    "org_ai_secret",
]
"""
The object type that the ACL applies to
"""

AclListPermission: TypeAlias = Literal[
    "create",
    "read",
    "update",
    "delete",
    "create_acls",
    "read_acls",
    "update_acls",
    "delete_acls",
]
"""
Each permission permits a certain type of operation on an object in the system

Permissions can be assigned to to objects on an individual basis, or grouped into roles
"""

AclListRestrictObjectType: TypeAlias = Literal[
    "organization",
    "project",
    "experiment",
    "dataset",
    "prompt",
    "prompt_session",
    "group",
    "role",
    "org_member",
    "project_log",
    "org_project",
    "org_audit_logs",
    "project_group",
    "ai_secret",
    "org_ai_secret",
]
"""
The object type that the ACL applies to
"""

AclListRoleId: TypeAlias = str
"""
Id of the role the ACL grants. Exactly one of `permission` and `role_id` will be provided
"""

AclListUserId: TypeAlias = str
"""
Id of the user the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
"""


class Acl(TypedDict):
    _object_org_id: str
    """
    The organization the ACL's referred object belongs to
    """
    created: NotRequired[str | None]
    """
    Date of acl creation
    """
    group_id: NotRequired[str | None]
    """
    Id of the group the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
    """
    id: str
    """
    Unique identifier for the acl
    """
    object_id: str
    """
    The id of the object the ACL applies to
    """
    object_type: AclObjectType
    permission: NotRequired[Permission | None]
    """
    Permission the ACL grants. Exactly one of `permission` and `role_id` will be provided
    """
    restrict_object_type: NotRequired[AclObjectType | None]
    """
    When setting a permission directly, optionally restricts the permission grant to just the specified object type. Cannot be set alongside a `role_id`.
    """
    role_id: NotRequired[str | None]
    """
    Id of the role the ACL grants. Exactly one of `permission` and `role_id` will be provided
    """
    user_id: NotRequired[str | None]
    """
    Id of the user the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
    """


class AclBatchUpdateResponse(TypedDict):
    added_acls: Sequence[Acl]
    removed_acls: Sequence[Acl]


class AclItem(TypedDict):
    group_id: NotRequired[str | None]
    """
    Id of the group the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
    """
    object_id: str
    """
    The id of the object the ACL applies to
    """
    object_type: AclObjectType
    permission: NotRequired[Permission | None]
    """
    Permission the ACL grants. Exactly one of `permission` and `role_id` will be provided
    """
    restrict_object_type: NotRequired[AclObjectType | None]
    """
    When setting a permission directly, optionally restricts the permission grant to just the specified object type. Cannot be set alongside a `role_id`.
    """
    role_id: NotRequired[str | None]
    """
    Id of the role the ACL grants. Exactly one of `permission` and `role_id` will be provided
    """
    user_id: NotRequired[str | None]
    """
    Id of the user the ACL applies to. Exactly one of `user_id` and `group_id` will be provided
    """


AclListOrgResponse: TypeAlias = Sequence[Acl]


class GetAclResponse(TypedDict):
    objects: Sequence[Acl]
    """
    A list of acl objects
    """


class AclBatchUpdateRequest(TypedDict):
    add_acls: NotRequired[Sequence[AclItem] | None]
    remove_acls: NotRequired[Sequence[AclItem] | None]
