# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 768a7ba86547c3d62db1818f63c9cccfeb77584e11d105f3f8ed014603fbb6db

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class Agent(TypedDict):
    created: NotRequired[str | None]
    """
    Date of agent creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the agent
    """
    id: str
    """
    Unique identifier for the agent
    """
    kind: str
    """
    Agent classification: 'custom' for customer-defined agents, 'loop' for built-in Loop agents.
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the agent
    """
    name: str
    """
    Name of the agent. Within a project, agent names are unique
    """
    project_id: str
    """
    Unique identifier for the project that the agent belongs under
    """
    slug: str
    """
    Stable, URL-safe identifier for the agent, unique within its project.
    """
    user_id: str


AgentIdParam: TypeAlias = str
"""
Agent id
"""

AgentName: TypeAlias = str
"""
Name of the agent to search for
"""


class CreateAgent(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the agent
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the agent
    """
    name: str
    """
    Name of the agent. Within a project, agent names are unique
    """
    project_id: str
    """
    Unique identifier for the project that the agent belongs under
    """


class GetAgentResponse(TypedDict):
    objects: Sequence[Agent]
    """
    A list of agent objects
    """


class PatchAgent(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the agent
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the agent
    """
    name: NotRequired[str | None]
    """
    Name of the agent. Within a project, agent names are unique
    """
