# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 128468e1d34987f9269038e4416b7a97fafb05d9
# OpenAPI spec SHA-256: c709dafda419ca01dfceeaaa8b17f258f3464fa4352e9619c2dcf5050259dc5d
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: eca638da8cc3bcb1caddd3e11ecd7ae52a79dc78dffabdb0d376ad77c0bc382d

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class AISecret(TypedDict):
    created: NotRequired[str | None]
    """
    Date of AI secret creation
    """
    id: str
    """
    Unique identifier for the AI secret
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    name: str
    """
    Name of the AI secret
    """
    org_id: str
    """
    Unique identifier for the organization
    """
    preview_secret: NotRequired[str | None]
    secret_updated_at: NotRequired[str | None]
    """
    Date of last update to the encrypted secret value itself
    """
    secret_updated_by_user_id: NotRequired[str | None]
    """
    User id of the last update to the encrypted secret value
    """
    type: NotRequired[str | None]
    updated_at: NotRequired[str | None]
    """
    Date of last AI secret update
    """


AISecretType: TypeAlias = str | Sequence[str]

AiSecretIdParam: TypeAlias = str
"""
AiSecret id
"""

AiSecretName: TypeAlias = str
"""
Name of the ai_secret to search for
"""


class CreateAISecret(TypedDict):
    metadata: NotRequired[Mapping[str, Any] | None]
    name: str
    """
    Name of the AI secret
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the AI Secret belongs in.
    """
    secret: NotRequired[str | None]
    """
    Secret value. If omitted in a PUT request, the existing secret value will be left intact, not replaced with null.
    """
    type: NotRequired[str | None]


class DeleteAISecret(TypedDict):
    name: str
    """
    Name of the AI secret
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the AI Secret belongs in.
    """


class GetAiSecretResponse(TypedDict):
    objects: Sequence[AISecret]
    """
    A list of ai_secret objects
    """


class PatchAISecret(TypedDict):
    metadata: NotRequired[Mapping[str, Any] | None]
    name: NotRequired[str | None]
    """
    Name of the AI secret
    """
    secret: NotRequired[str | None]
    type: NotRequired[str | None]
