# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 50b04c997c9d1bc8a29b0f88d5448dd3d6009b77f60107234e16850d2613df9c

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class ApiKey(TypedDict):
    created: NotRequired[str | None]
    """
    Date of api key creation
    """
    expires_at: NotRequired[str | None]
    """
    Date at which the API key expires. If null, the key never expires.
    """
    id: str
    """
    Unique identifier for the api key
    """
    name: str
    """
    Name of the api key
    """
    org_id: NotRequired[str | None]
    """
    Unique identifier for the organization
    """
    preview_name: str
    user_email: NotRequired[str | None]
    """
    The user's email
    """
    user_family_name: NotRequired[str | None]
    """
    Family name of the user
    """
    user_given_name: NotRequired[str | None]
    """
    Given name of the user
    """
    user_id: NotRequired[str | None]
    """
    Unique identifier for the user
    """


ApiKeyIdParam: TypeAlias = str
"""
ApiKey id
"""

ApiKeyName: TypeAlias = str
"""
Name of the api_key to search for
"""


class GetApiKeyResponse(TypedDict):
    objects: Sequence[ApiKey]
    """
    A list of api_key objects
    """
