# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 9daf27f19d9e0340304d7a3e7d0edb28380b94c6
# OpenAPI spec SHA-256: 5ec753c0263c0c44cd04f741edfc7e8bad491cc25a2113d029e84edc076520f0
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 4f44bc62a969364392528ed2e8919cb5ba98b5a57aa742fe184571dcc61443da

from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence
from typing_extensions import NotRequired

EndingBefore: TypeAlias = str
"""
Pagination cursor id.

For example, if the initial item in the last page you fetched had an id of `foo`, pass `ending_before=foo` to fetch the previous page. Note: you may only pass one of `starting_after` and `ending_before`
"""

FunctionTypeEnum: TypeAlias = (
    Literal[
        "llm",
        "scorer",
        "task",
        "tool",
        "custom_view",
        "preprocessor",
        "facet",
        "classifier",
        "tag",
        "parameters",
        "sandbox",
    ]
    | None
)
"""
The type of global function. Defaults to 'scorer'.
"""

Ids: TypeAlias = str | Sequence[str]
"""
Filter search results to a particular set of object IDs. To specify a list of IDs, include the query param multiple times
"""

OrgName: TypeAlias = str
"""
Filter search results to within a particular organization
"""

ProjectName: TypeAlias = str
"""
Name of the project to search for
"""

StartingAfter: TypeAlias = str
"""
Pagination cursor id.

For example, if the final item in the last page you fetched had an id of `foo`, pass `starting_after=foo` to fetch the next page. Note: you may only pass one of `starting_after` and `ending_before`
"""
