# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: ba9fb3e88d4db738617c2bb521c2b0942619e1cb3a940b466c0290cf8fa5503a

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class EnvVar(TypedDict):
    created: NotRequired[str | None]
    """
    Date of environment variable creation
    """
    id: str
    """
    Unique identifier for the environment variable
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    Optional metadata associated with the environment variable when managed via the function secrets API
    """
    name: str
    """
    The name of the environment variable
    """
    object_id: str
    """
    The id of the object the environment variable is scoped for
    """
    object_type: Literal["organization", "project", "function"]
    """
    The type of the object the environment variable is scoped for
    """
    preview_secret: NotRequired[str | None]
    """
    Redacted preview of the stored secret value
    """
    secret_category: NotRequired[Literal["env_var", "ai_provider", "sandbox_provider"]]
    """
    The category of the secret: env_var for regular environment variables, ai_provider for AI provider API keys
    """
    secret_type: NotRequired[str | None]
    """
    Optional classification for the secret (for example, the AI provider name)
    """
    secret_updated_at: NotRequired[str | None]
    """
    Date of last update to the encrypted secret value itself
    """
    secret_updated_by_user_id: NotRequired[str | None]
    """
    User id of the last update to the encrypted secret value
    """
    used: NotRequired[str | None]
    """
    Date the environment variable was last used
    """


EnvVarIdParam: TypeAlias = str
"""
EnvVar id
"""

EnvVarName: TypeAlias = str
"""
Name of the env_var to search for
"""

EnvVarObjectId: TypeAlias = str
"""
The id of the object the environment variable is scoped for
"""

EnvVarObjectType: TypeAlias = Literal["organization", "project", "function"]
"""
The type of the object the environment variable is scoped for
"""


class GetEnvVarResponse(TypedDict):
    objects: Sequence[EnvVar]
    """
    A list of env_var objects
    """
