# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 128468e1d34987f9269038e4416b7a97fafb05d9
# OpenAPI spec SHA-256: c709dafda419ca01dfceeaaa8b17f258f3464fa4352e9619c2dcf5050259dc5d
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 12c91d9e0b397ae1a547094c05bb016bdf4fe2bd09683493f972b5c8d470fcea

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class EnvVar(TypedDict):
    created: NotRequired[str | None]
    """
    Date of environment variable creation
    """
    id: str
    """
    Unique identifier for the environment variable
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    Optional metadata associated with the environment variable when managed via the function secrets API
    """
    name: str
    """
    The name of the environment variable
    """
    object_id: str
    """
    The id of the object the environment variable is scoped for
    """
    object_type: Literal["organization", "project", "function", "mcp_server"]
    """
    The type of the object the environment variable is scoped for
    """
    preview_secret: NotRequired[str | None]
    """
    Redacted preview of the stored secret value
    """
    secret_category: NotRequired[Literal["env_var", "ai_provider", "sandbox_provider"]]
    """
    The category of the secret: env_var for regular environment variables, ai_provider for AI provider API keys
    """
    secret_type: NotRequired[str | None]
    """
    Optional classification for the secret (for example, the AI provider name)
    """
    secret_updated_at: NotRequired[str | None]
    """
    Date of last update to the encrypted secret value itself
    """
    secret_updated_by_user_id: NotRequired[str | None]
    """
    User id of the last update to the encrypted secret value
    """
    used: NotRequired[str | None]
    """
    Date the environment variable was last used
    """


EnvVarIdParam: TypeAlias = str
"""
EnvVar id
"""

EnvVarName: TypeAlias = str
"""
Name of the env_var to search for
"""

EnvVarObjectId: TypeAlias = str
"""
The id of the object the environment variable is scoped for
"""

EnvVarObjectType: TypeAlias = Literal["organization", "project", "function", "mcp_server"]
"""
The type of the object the environment variable is scoped for
"""


class GetEnvVarResponse(TypedDict):
    objects: Sequence[EnvVar]
    """
    A list of env_var objects
    """
