# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 977acecd3d3b6bf063a18a966522e55dd190fa6e1d4e52130ee8761a200b2c3b

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateEnvironment(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the environment
    """
    name: str
    """
    Name of the environment
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the environment belongs in.
    """
    slug: str
    """
    A url-friendly, unique identifier for the environment within an organization
    """


class Environment(TypedDict):
    created: NotRequired[str | None]
    """
    Date of environment creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of environment deletion, or null if the environment is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the environment
    """
    id: str
    """
    Unique identifier for the environment
    """
    name: str
    """
    Name of the environment
    """
    org_id: str
    """
    Unique identifier for the organization that the environment belongs under
    """
    slug: str
    """
    A url-friendly, unique identifier for the environment within an organization
    """


class ListEnvironmentsResponse(TypedDict):
    objects: Sequence[Environment]


class PatchEnvironment(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the environment
    """
    name: NotRequired[str | None]
    """
    Name of the environment
    """
    slug: NotRequired[str | None]
    """
    A url-friendly, unique identifier for the environment within an organization
    """
