# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 8f75af48b162ca2c86ab19fb6a4850e12eac3b9e2376887cad73109e42c833e5

from typing import Any, Literal, TypeAlias, TypedDict
from typing_extensions import NotRequired
from collections.abc import Mapping, Sequence

from .common import ChatCompletionMessageParam, FunctionTypeEnum, FunctionTypeEnumNullish, PromptDataNullish

AclObjectType: TypeAlias = Literal[
    "organization",
    "project",
    "experiment",
    "dataset",
    "prompt",
    "prompt_session",
    "group",
    "role",
    "org_member",
    "project_log",
    "org_project",
    "org_audit_logs",
    "project_group",
    "ai_secret",
    "org_ai_secret",
]
"""
The object type that the ACL applies to
"""


class Facet(TypedDict):
    embedding_model: NotRequired[str]
    """
    The embedding model to use for vectorizing facet results.
    """
    model: NotRequired[str]
    """
    The model to use for facet extraction
    """
    name: str
    """
    The name of the facet
    """
    no_match_pattern: NotRequired[str]
    """
    Regex pattern to identify outputs that do not match the facet. If the output matches, the facet will be saved as 'no_match'
    """
    prompt: str
    """
    The prompt to use for LLM extraction. The preprocessed text will be provided as context.
    """


class Position(TypedDict):
    type: Literal["task"]


class Position1(TypedDict):
    index: int
    type: Literal["scorer"]


class Position2(TypedDict):
    index: int
    type: Literal["classifier"]


class Location(TypedDict):
    eval_name: str
    position: Position | Position1 | Position2
    type: Literal["experiment"]


class Location1(TypedDict):
    index: int
    type: Literal["function"]


class SandboxSpec(TypedDict):
    provider: Literal["modal"]
    snapshot_ref: str
    """
    sandbox snapshot ref
    """


class SandboxSpec1(TypedDict):
    provider: Literal["lambda"]


class Location2(TypedDict):
    entrypoints: NotRequired[Sequence[str]]
    """
    Which entrypoints to execute in the sandbox
    """
    eval_name: str
    evaluator_definition: NotRequired[Any | None]
    """
    Definition of current evaluator with parameters
    """
    parameters: NotRequired[Mapping[str, Any]]
    """
    Parameter values for sandbox eval execution
    """
    sandbox_spec: SandboxSpec | SandboxSpec1
    type: Literal["sandbox"]


class RuntimeContext(TypedDict):
    runtime: Literal["node", "python", "browser", "quickjs"]
    version: str


class CodeBundle(TypedDict):
    bundle_id: NotRequired[str | None]
    location: Location | Location1 | Location2
    preview: NotRequired[str | None]
    """
    A preview of the code
    """
    runtime_context: RuntimeContext


class FunctionSchema(TypedDict):
    parameters: NotRequired[Any | None]
    returns: NotRequired[Any | None]


class Origin(TypedDict):
    internal: NotRequired[bool | None]
    """
    The function exists for internal purposes and should not be displayed in the list of functions.
    """
    object_id: str
    """
    Id of the object the function is originating from
    """
    object_type: AclObjectType


class FacetPreprocessorId1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class FacetPreprocessorId3(TypedDict):
    code: str
    """
    The complete JavaScript preprocessor implementation, including its handler.
    """
    type: Literal["inline"]


class FunctionData1(TypedDict):
    type: Literal["prompt"]


class Data(CodeBundle):
    type: Literal["bundle"]


class Data1(TypedDict):
    code: str
    code_hash: NotRequired[str]
    """
    SHA256 hash of the code, computed at save time
    """
    runtime_context: RuntimeContext
    type: Literal["inline"]


class FunctionData2(TypedDict):
    data: Data | Data1
    type: Literal["code"]


class FunctionData3(TypedDict):
    endpoint: str
    eval_name: str
    parameters: Mapping[str, Any]
    parameters_version: NotRequired[str | None]
    """
    The version (transaction ID) of the parameters being used
    """
    type: Literal["remote_eval"]


class FieldSchema(TypedDict):
    additionalProperties: NotRequired[bool]
    properties: Mapping[str, Mapping[str, Any]]
    required: NotRequired[Sequence[str]]
    type: Literal["object"]


FunctionData5 = TypedDict(
    "FunctionData5",
    {
        "__schema": FieldSchema,
        "data": Mapping[str, Any],
        "type": Literal["parameters"],
    },
)


class FunctionDataNullish1(TypedDict):
    type: Literal["prompt"]


class Data2(CodeBundle):
    type: Literal["bundle"]


class Data3(TypedDict):
    code: str
    code_hash: NotRequired[str]
    """
    SHA256 hash of the code, computed at save time
    """
    runtime_context: RuntimeContext
    type: Literal["inline"]


class FunctionDataNullish2(TypedDict):
    data: Data2 | Data3
    type: Literal["code"]


class FunctionDataNullish3(TypedDict):
    endpoint: str
    eval_name: str
    parameters: Mapping[str, Any]
    parameters_version: NotRequired[str | None]
    """
    The version (transaction ID) of the parameters being used
    """
    type: Literal["remote_eval"]


FunctionDataNullish5 = TypedDict(
    "FunctionDataNullish5",
    {
        "__schema": FieldSchema,
        "data": Mapping[str, Any],
        "type": Literal["parameters"],
    },
)

FunctionIdParam: TypeAlias = str
"""
Function id
"""

FunctionIdRef: TypeAlias = Mapping[str, Any]

FunctionName: TypeAlias = str
"""
Name of the function to search for
"""


class Source(TypedDict):
    node: str
    """
    The id of the node in the graph
    """
    variable: str


class Target(TypedDict):
    node: str
    """
    The id of the node in the graph
    """
    variable: str


class GraphEdge(TypedDict):
    purpose: Literal["control", "data", "messages"]
    """
    The purpose of the edge
    """
    source: Source
    target: Target


class Position3(TypedDict):
    x: float
    """
    The x position of the node
    """
    y: float
    """
    The y position of the node
    """


class GraphNode1(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    function: FunctionIdRef
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["function"]


class GraphNode2(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["input"]
    """
    The input to the graph
    """


class GraphNode3(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["output"]
    """
    The output of the graph
    """


class GraphNode4(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["literal"]
    value: NotRequired[Any | None]
    """
    A literal value to be returned
    """


class GraphNode5(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    expr: str
    """
    A BTQL expression to be evaluated
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["btql"]


class GraphNode6(TypedDict):
    condition: NotRequired[str | None]
    """
    A BTQL expression to be evaluated
    """
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["gate"]


class GraphNode7(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    type: Literal["aggregator"]


class PromptBlockData2(TypedDict):
    content: str
    type: Literal["completion"]


class SourceFacetFunction1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class SourceFacetFunction2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class SourceFacetFunction3(TypedDict):
    pass


class SourceFacetFunction4(SourceFacetFunction1, SourceFacetFunction3):
    pass


class SourceFacetFunction5(SourceFacetFunction2, SourceFacetFunction3):
    pass


class SourceFacetFunction6(SourceFacetFunction1, SourceFacetFunction3):
    pass


class SourceFacetFunction7(SourceFacetFunction2, SourceFacetFunction3):
    pass


SourceFacetFunction: TypeAlias = (
    SourceFacetFunction4 | SourceFacetFunction5 | SourceFacetFunction6 | SourceFacetFunction7
)


class TopicMapGenerationSettings(TypedDict):
    algorithm: Literal["hdbscan", "kmeans", "community"]
    dimension_reduction: Literal["umap", "pca", "none"]
    hierarchy_threshold: NotRequired[int]
    min_cluster_size: NotRequired[int]
    min_samples: NotRequired[int]
    n_clusters: NotRequired[int]
    naming_model: NotRequired[str]
    sample_size: NotRequired[int]


class FacetPreprocessorId2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


FacetPreprocessorId: TypeAlias = FacetPreprocessorId1 | FacetPreprocessorId2 | FacetPreprocessorId3 | None
"""
The saved, global, or inline preprocessor to use for facet extraction. If not provided, the project default preprocessor will be used, falling back to the global 'thread' preprocessor.
"""


class FunctionData4(TypedDict):
    config: NotRequired[Mapping[str, Any] | None]
    """
    Configuration options to pass to the global function (e.g., for preprocessor customization)
    """
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class FunctionDataNullish4(TypedDict):
    config: NotRequired[Mapping[str, Any] | None]
    """
    Configuration options to pass to the global function (e.g., for preprocessor customization)
    """
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class TopicMapData(TypedDict):
    automation_btql_filter: NotRequired[str]
    """
    Automation-level BTQL filter that was applied when this version was generated. Absent on versions generated before this was recorded.
    """
    btql_filter: NotRequired[str]
    """
    Per-topic-map BTQL filter that was applied when this version was generated. Absent on versions generated before this was recorded.
    """
    bundle_key: NotRequired[str]
    """
    Key of the topic map bundle in code_bundles bucket
    """
    disable_reconciliation: NotRequired[bool]
    """
    Whether new topic generation should ignore the previously saved report during reconciliation. Defaults to false when omitted.
    """
    distance_threshold: NotRequired[float]
    """
    Maximum distance to nearest centroid. If exceeded, returns no_match.
    """
    embedding_model: str
    """
    The embedding model to use for embedding facet values
    """
    generation_settings: NotRequired[TopicMapGenerationSettings]
    reconcile_mode: NotRequired[Literal["evolve", "names_only"]]
    """
    How reconciliation carries the previous map forward: "evolve" re-routes new samples into the previous topics before naming; "names_only" keeps the fresh clustering and carries only topic ids/names. Defaults to "names_only" when omitted.
    """
    report_key: NotRequired[str]
    """
    Key of the clustering report in code_bundles bucket
    """
    source_facet: str
    """
    Materialized facet field name used when source_facet_function is absent
    """
    source_facet_function: NotRequired[SourceFacetFunction]
    topic_names: NotRequired[Mapping[str, str]]
    """
    Mapping from topic_id to topic name
    """
    type: Literal["topic_map"]


class TopicMap(TypedDict):
    function_name: str
    """
    The name of the topic map function
    """
    topic_map_data: TopicMapData
    topic_map_id: NotRequired[str]
    """
    The id of the topic map function
    """


class BatchedFacetData(TypedDict):
    facets: Sequence[Facet]
    preprocessor: NotRequired[FacetPreprocessorId]
    topic_maps: NotRequired[Mapping[str, Sequence[TopicMap]]]
    """
    Topic maps that depend on facets in this batch, keyed by source facet name. Each source facet can have multiple topic maps.
    """
    type: Literal["batched_facet"]


class FacetData(TypedDict):
    embedding_model: NotRequired[str]
    """
    The embedding model to use for vectorizing facet results.
    """
    model: NotRequired[str]
    """
    The model to use for facet extraction
    """
    no_match_pattern: NotRequired[str]
    """
    Regex pattern to identify outputs that do not match the facet. If the output matches, the facet will be saved as 'no_match'
    """
    preprocessor: NotRequired[FacetPreprocessorId]
    prompt: str
    """
    The prompt to use for LLM extraction. The preprocessed text will be provided as context.
    """
    type: Literal["facet"]


class PromptBlockData1(TypedDict):
    messages: Sequence[ChatCompletionMessageParam]
    tools: NotRequired[str]
    type: Literal["chat"]


PromptBlockData: TypeAlias = PromptBlockData1 | PromptBlockData2


class GraphNode8(TypedDict):
    description: NotRequired[str | None]
    """
    The description of the node
    """
    position: NotRequired[Position3 | None]
    """
    The position of the node
    """
    prompt: PromptBlockData
    type: Literal["prompt_template"]


GraphNode: TypeAlias = (
    GraphNode1 | GraphNode2 | GraphNode3 | GraphNode4 | GraphNode5 | GraphNode6 | GraphNode7 | GraphNode8
)


class GraphData(TypedDict):
    edges: Mapping[str, GraphEdge]
    nodes: Mapping[str, GraphNode]
    type: Literal["graph"]


FunctionData: TypeAlias = (
    FunctionData1
    | FunctionData2
    | GraphData
    | FunctionData3
    | FunctionData4
    | FacetData
    | BatchedFacetData
    | FunctionData5
    | TopicMapData
)

FunctionDataNullish: TypeAlias = (
    FunctionDataNullish1
    | FunctionDataNullish2
    | GraphData
    | FunctionDataNullish3
    | FunctionDataNullish4
    | FacetData
    | BatchedFacetData
    | FunctionDataNullish5
    | TopicMapData
    | None
)


class PatchFunction(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_data: NotRequired[FunctionDataNullish]
    name: NotRequired[str | None]
    """
    Name of the prompt
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class CreateFunction(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_data: FunctionData
    function_schema: NotRequired[FunctionSchema | None]
    """
    JSON schema for the function's parameters and return type
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    name: str
    """
    Name of the prompt
    """
    origin: NotRequired[Origin | None]
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class Function(TypedDict):
    _xact_id: str
    """
    The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the prompt (see the `version` parameter)
    """
    created: NotRequired[str | None]
    """
    Date of prompt creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_data: FunctionData
    function_schema: NotRequired[FunctionSchema | None]
    """
    JSON schema for the function's parameters and return type
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    id: str
    """
    Unique identifier for the prompt
    """
    log_id: Literal["p"]
    """
    A literal 'p' which identifies the object as a project prompt
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the prompt
    """
    name: str
    """
    Name of the prompt
    """
    org_id: str
    """
    Unique identifier for the organization
    """
    origin: NotRequired[Origin | None]
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class GetFunctionResponse(TypedDict):
    objects: Sequence[Function]
    """
    A list of function objects
    """
