# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 96dc21bc161bc5a0f33ccdd9b5e660ed251030c4b7f59a59563297b101ae4193

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateGroup(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the group
    """
    member_groups: NotRequired[Sequence[str] | None]
    """
    Ids of the groups this group inherits from

    An inheriting group has all the users contained in its member groups, as well as all of their inherited users
    """
    member_users: NotRequired[Sequence[str] | None]
    """
    Ids of users which belong to this group
    """
    name: str
    """
    Name of the group
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the group belongs in.
    """


class Group(TypedDict):
    created: NotRequired[str | None]
    """
    Date of group creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of group deletion, or null if the group is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the group
    """
    id: str
    """
    Unique identifier for the group
    """
    member_groups: NotRequired[Sequence[str] | None]
    """
    Ids of the groups this group inherits from

    An inheriting group has all the users contained in its member groups, as well as all of their inherited users
    """
    member_users: NotRequired[Sequence[str] | None]
    """
    Ids of users which belong to this group
    """
    name: str
    """
    Name of the group
    """
    org_id: str
    """
    Unique id for the organization that the group belongs under

    It is forbidden to change the org after creating a group
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the group
    """


GroupIdParam: TypeAlias = str
"""
Group id
"""

GroupName: TypeAlias = str
"""
Name of the group to search for
"""


class PatchGroup(TypedDict):
    add_member_groups: NotRequired[Sequence[str] | None]
    """
    A list of group IDs to add to the group's inheriting-from set
    """
    add_member_users: NotRequired[Sequence[str] | None]
    """
    A list of user IDs to add to the group
    """
    description: NotRequired[str | None]
    """
    Textual description of the group
    """
    name: NotRequired[str | None]
    """
    Name of the group
    """
    remove_member_groups: NotRequired[Sequence[str] | None]
    """
    A list of group IDs to remove from the group's inheriting-from set
    """
    remove_member_users: NotRequired[Sequence[str] | None]
    """
    A list of user IDs to remove from the group
    """


class GetGroupResponse(TypedDict):
    objects: Sequence[Group]
    """
    A list of group objects
    """
