# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: b23ca69ae5400afdc852a1fa6fc61329bb4a1cf34d6de4af08098505184d46c7

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateMCPServer(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the MCP server
    """
    name: str
    """
    Name of the MCP server. Within a project, MCP server names are unique
    """
    project_id: str
    """
    Unique identifier for the project that the MCP server belongs under
    """
    url: str
    """
    URL of the MCP server endpoint
    """


class MCPServer(TypedDict):
    created: NotRequired[str | None]
    """
    Date of MCP server creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of MCP server deletion, or null if the MCP server is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the MCP server
    """
    id: str
    """
    Unique identifier for the MCP server
    """
    name: str
    """
    Name of the MCP server. Within a project, MCP server names are unique
    """
    project_id: str
    """
    Unique identifier for the project that the MCP server belongs under
    """
    url: str
    """
    URL of the MCP server endpoint
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the MCP server
    """


McpServerIdParam: TypeAlias = str
"""
McpServer id
"""

McpServerName: TypeAlias = str
"""
Name of the mcp_server to search for
"""


class PatchMCPServer(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the MCP server
    """
    name: NotRequired[str | None]
    """
    Name of the MCP server. Within a project, MCP server names are unique
    """
    url: NotRequired[str | None]
    """
    URL of the MCP server endpoint
    """


class GetMcpServerResponse(TypedDict):
    objects: Sequence[MCPServer]
    """
    A list of mcp_server objects
    """
