# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: d1615033766f1c4d0f8e47933f414909e88c91e3e031941f616bd50c17b4988d

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import Config4, RetentionObjectType

OrgAutomationIdParam: TypeAlias = str
"""
OrgAutomation id
"""

OrgAutomationName: TypeAlias = str
"""
Name of the org_automation to search for
"""


class Config(TypedDict):
    event_type: Literal["retention"]
    """
    The type of automation.
    """
    object_type: RetentionObjectType
    retention_days: int
    """
    The number of days to retain the object
    """


class CreateOrgAutomation(TypedDict):
    config: Config
    """
    The configuration for the org automation rule
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    name: str
    """
    Name of the project automation
    """
    org_id: str
    """
    Unique identifier for the organization that the org automation belongs under
    """


class OrgAutomation(TypedDict):
    config: Config4
    """
    The configuration for the org automation rule
    """
    created: NotRequired[str | None]
    """
    Date of project automation creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    id: str
    """
    Unique identifier for the project automation
    """
    name: str
    """
    Name of the project automation
    """
    org_id: str
    """
    Unique identifier for the organization that the org automation belongs under
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project automation
    """


class PatchOrgAutomation(TypedDict):
    config: NotRequired[Config4 | None]
    """
    The configuration for the org automation rule
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    name: NotRequired[str | None]
    """
    Name of the project automation
    """


class GetOrgAutomationResponse(TypedDict):
    objects: Sequence[OrgAutomation]
    """
    A list of org_automation objects
    """
