# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 8757f0faef2942e8e06cb708ffb9676058767f9cc305bf1cde5d49a3e8905f71

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

ImageRenderingMode: TypeAlias = Literal["auto", "click_to_load", "blocked"] | None
"""
Controls how images are rendered in the UI: 'auto' loads images automatically, 'click_to_load' shows a placeholder until clicked, 'blocked' prevents image loading entirely
"""


class Organization(TypedDict):
    api_url: NotRequired[str | None]
    created: NotRequired[str | None]
    """
    Date of organization creation
    """
    id: str
    """
    Unique identifier for the organization
    """
    image_rendering_mode: NotRequired[ImageRenderingMode | None]
    is_dataplane_private: NotRequired[bool | None]
    is_universal_api: NotRequired[bool | None]
    name: str
    """
    Name of the organization
    """
    proxy_url: NotRequired[str | None]
    realtime_url: NotRequired[str | None]


OrganizationIdParam: TypeAlias = str
"""
Organization id
"""


class PatchOrganization(TypedDict):
    api_url: NotRequired[str | None]
    image_rendering_mode: NotRequired[ImageRenderingMode | None]
    is_dataplane_private: NotRequired[bool | None]
    is_universal_api: NotRequired[bool | None]
    name: NotRequired[str | None]
    """
    Name of the organization
    """
    proxy_url: NotRequired[str | None]
    realtime_url: NotRequired[str | None]


class ServiceAccount(TypedDict):
    name: str
    token_expires_in_seconds: NotRequired[int | None]
    """
    Number of seconds from now after which the initial service token should expire. If omitted, the token never expires.
    """
    token_name: NotRequired[str | None]
    """
    Optional name of an initial service token to create for the new service account. This is a narrow compatibility carve-out only on PATCH /v1/organization/members. When this field is set, the request must be authenticated with a service token that has organization-owner permissions, not a user API key.
    """


class InviteUsers(TypedDict):
    emails: NotRequired[Sequence[str] | None]
    """
    Emails of users to invite
    """
    group_id: NotRequired[str | None]
    """
    Singular form of group_ids
    """
    group_ids: NotRequired[Sequence[str] | None]
    """
    Optional list of group ids to add newly-invited users to.
    """
    group_name: NotRequired[str | None]
    """
    Singular form of group_names
    """
    group_names: NotRequired[Sequence[str] | None]
    """
    Optional list of group names to add newly-invited users to.
    """
    ids: NotRequired[Sequence[str] | None]
    """
    Ids of existing users to invite
    """
    send_invite_emails: NotRequired[bool | None]
    """
    If true, send invite emails to the users who wore actually added
    """
    service_accounts: NotRequired[Sequence[ServiceAccount] | None]
    """
    Service accounts to create. PATCH /v1/organization/members is the compatibility layer that accepts both plain service-account creation and the narrower token_name create-and-mint carve-out.
    """


class RemoveUsers(TypedDict):
    emails: NotRequired[Sequence[str] | None]
    """
    Emails of users to remove
    """
    ids: NotRequired[Sequence[str] | None]
    """
    Ids of users to remove
    """


class PatchOrganizationMembers(TypedDict):
    invite_users: NotRequired[InviteUsers | None]
    """
    Users to invite to the organization
    """
    org_id: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, or in case you want to explicitly assert the organization you are modifying, you may specify the id of the organization.
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, or in case you want to explicitly assert the organization you are modifying, you may specify the name of the organization.
    """
    remove_users: NotRequired[RemoveUsers | None]
    """
    Users to remove from the organization
    """


class AddedUser(TypedDict):
    api_key: NotRequired[str | None]
    email: NotRequired[str | None]
    id: str
    token_name: NotRequired[str | None]


class PatchOrganizationMembersOutput(TypedDict):
    added_users: NotRequired[Sequence[AddedUser] | None]
    """
    The users who were added by this request. api_key and token_name are only present for the inline service-account create-and-mint compatibility path.
    """
    org_id: str
    """
    The id of the org that was modified.
    """
    send_email_error: NotRequired[str | None]
    """
    If invite emails failed to send for some reason, the patch operation will still complete, but we will return an error message here
    """
    status: Literal["success"]


class GetOrganizationResponse(TypedDict):
    objects: Sequence[Organization]
    """
    A list of organization objects
    """
