# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: b640d57f8d16916eac9cbda4ac6d565638af2611ec914903004b88e105d25a53

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateProjectGroup(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the project group
    """
    name: str
    """
    Name of the project group
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the project group belongs in.
    """


class PatchProjectGroup(TypedDict):
    add_member_projects: NotRequired[Sequence[str] | None]
    """
    A list of project IDs to add to the project group
    """
    description: NotRequired[str | None]
    """
    Textual description of the project group
    """
    name: NotRequired[str | None]
    """
    Name of the project group
    """
    remove_member_projects: NotRequired[Sequence[str] | None]
    """
    A list of project IDs to remove from the project group
    """


class ProjectGroup(TypedDict):
    created: NotRequired[str | None]
    """
    Date of project group creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of project group deletion, or null if the project group is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the project group
    """
    id: str
    """
    Unique identifier for the project group
    """
    member_projects: Sequence[str]
    """
    Sorted ids of active projects in this project group
    """
    name: str
    """
    Name of the project group
    """
    org_id: str
    """
    Unique id for the organization that the project group belongs under

    It is forbidden to change the org after creating a project group
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project group
    """


ProjectGroupIdParam: TypeAlias = str
"""
ProjectGroup id
"""

ProjectGroupName: TypeAlias = str
"""
Name of the project_group to search for
"""


class GetProjectGroupResponse(TypedDict):
    objects: Sequence[ProjectGroup]
    """
    A list of project_group objects
    """
