# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 9daf27f19d9e0340304d7a3e7d0edb28380b94c6
# OpenAPI spec SHA-256: 5ec753c0263c0c44cd04f741edfc7e8bad491cc25a2113d029e84edc076520f0
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 9736eda7e5e0dd80b0e149a4275c4a94e8da78149af79cc692006076f109107f

from typing import Literal, TypeAlias, TypedDict
from typing_extensions import NotRequired
from collections.abc import Sequence


AppLimitParam: TypeAlias = int | None
"""
Limit the number of objects to return
"""


class CreateProject(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    name: str
    """
    Name of the project
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the project belongs in.
    """


EndingBefore: TypeAlias = str
"""
Pagination cursor id.

For example, if the initial item in the last page you fetched had an id of `foo`, pass `ending_before=foo` to fetch the previous page. Note: you may only pass one of `starting_after` and `ending_before`
"""


FunctionTypeEnum: TypeAlias = (
    Literal[
        "llm",
        "scorer",
        "task",
        "tool",
        "custom_view",
        "preprocessor",
        "facet",
        "classifier",
        "tag",
        "parameters",
        "sandbox",
    ]
    | None
)
"""
The type of global function. Defaults to 'scorer'.
"""


Ids: TypeAlias = str | Sequence[str]
"""
Filter search results to a particular set of object IDs. To specify a list of IDs, include the query param multiple times
"""


class NullableSavedFunctionId1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class NullableSavedFunctionId2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


NullableSavedFunctionId: TypeAlias = NullableSavedFunctionId1 | NullableSavedFunctionId2 | None
"""
Default preprocessor for this project. When set, functions that use preprocessors will use this instead of their built-in default.
"""


OrgName: TypeAlias = str
"""
Filter search results to within a particular organization
"""


ProjectIdParam: TypeAlias = str
"""
Project id
"""


ProjectName: TypeAlias = str
"""
Name of the project to search for
"""


class RemoteEvalSource(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    url: str


class SpanFieldOrderItem(TypedDict):
    column_id: str
    layout: NotRequired[Literal["full"] | Literal["two_column"] | None]
    object_type: str
    position: str


class ProjectSettings(TypedDict):
    baseline_experiment_id: NotRequired[str | None]
    """
    The id of the experiment to use as the default baseline for comparisons
    """
    comparison_key: NotRequired[str | None]
    """
    The key used to join two experiments (defaults to `input`)
    """
    default_preprocessor: NotRequired[NullableSavedFunctionId]
    disable_realtime_queries: NotRequired[bool | None]
    """
    If true, disable real-time queries for this project. This can improve query performance for high-volume logs.
    """
    remote_eval_sources: NotRequired[Sequence[RemoteEvalSource] | None]
    """
    The remote eval sources to use for the project
    """
    spanFieldOrder: NotRequired[Sequence[SpanFieldOrderItem] | None]
    """
    The order of the fields to display in the trace view
    """


StartingAfter: TypeAlias = str
"""
Pagination cursor id.

For example, if the final item in the last page you fetched had an id of `foo`, pass `starting_after=foo` to fetch the next page. Note: you may only pass one of `starting_after` and `ending_before`
"""


class PatchProject(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    """
    Name of the project
    """
    settings: NotRequired[ProjectSettings]
    user_id: NotRequired[str | None]


class Project(TypedDict):
    created: NotRequired[str | None]
    """
    Date of project creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of project deletion, or null if the project is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    id: str
    """
    Unique identifier for the project
    """
    name: str
    """
    Name of the project
    """
    org_id: str
    """
    Unique id for the organization that the project belongs under
    """
    settings: NotRequired[ProjectSettings | None]
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project
    """


class GetProjectResponse(TypedDict):
    objects: Sequence[Project]
    """
    A list of project objects
    """
