# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 66eed24b98cd0f5609c9f524230a61497f7fd77d
# OpenAPI spec SHA-256: 877ab1fd2a22c407af1975a2f880170fb5dc2d31f550c1ce611b407037e4f221
# datamodel-code-generator: 0.81.0
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: cd54c4ca982126df022c601a5e6047aba15572437f4bd6f8727fd407d07b246f

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import FunctionTypeEnum


class CreateProject(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    name: str
    """
    Name of the project
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the project belongs in.
    """
    project_group_name: NotRequired[str | None]
    """
    Create the project within the named project group in this organization. Requires project_group:update and either project_group_projects:create on the group or org_project:create on the organization.
    """


class NullableSavedFunctionId1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class NullableSavedFunctionId2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


NullableSavedFunctionId: TypeAlias = NullableSavedFunctionId1 | NullableSavedFunctionId2 | None
"""
Default preprocessor for this project. When set, functions that use preprocessors will use this instead of their built-in default.
"""

ProjectIdParam: TypeAlias = str
"""
Project id
"""


class RemoteEvalSource(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    url: str


class SpanFieldOrderItem(TypedDict):
    column_id: str
    layout: NotRequired[Literal["full"] | Literal["two_column"] | None]
    object_type: str
    position: str


class ProjectSettings(TypedDict):
    baseline_experiment_id: NotRequired[str | None]
    """
    The id of the experiment to use as the default baseline for comparisons
    """
    blind_reviews: NotRequired[bool | None]
    """
    If true, hide peer review scores, comments, and aggregate results from reviewers without project update permissions until they submit their own review.
    """
    coding_agent_insights_dashboard: NotRequired[bool | None]
    """
    If true, enable the agent insights dashboard for this project.
    """
    comparison_key: NotRequired[str | None]
    """
    The key used to join two experiments (defaults to `input`)
    """
    default_preprocessor: NotRequired[NullableSavedFunctionId]
    disable_realtime_queries: NotRequired[bool | None]
    """
    If true, disable real-time queries for this project. This can improve query performance for high-volume logs.
    """
    monitor_charts_use_metrics_start: NotRequired[bool | None]
    """
    If true, use metrics.start rather than created for monitor chart time bucket dimensions.
    """
    remote_eval_sources: NotRequired[Sequence[RemoteEvalSource] | None]
    """
    The remote eval sources to use for the project
    """
    require_all_human_review_scores: NotRequired[bool | None]
    """
    If true, automatically complete a review after every assigned reviewer fills all human review scores visible to them.
    """
    spanFieldOrder: NotRequired[Sequence[SpanFieldOrderItem] | None]
    """
    The order of the fields to display in the trace view
    """


class PatchProject(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    """
    Name of the project
    """
    settings: NotRequired[ProjectSettings]
    user_id: NotRequired[str | None]


class Project(TypedDict):
    created: NotRequired[str | None]
    """
    Date of project creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of project deletion, or null if the project is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    id: str
    """
    Unique identifier for the project
    """
    name: str
    """
    Name of the project
    """
    org_id: str
    """
    Unique id for the organization that the project belongs under
    """
    settings: NotRequired[ProjectSettings | None]
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project
    """


class GetProjectResponse(TypedDict):
    objects: Sequence[Project]
    """
    A list of project objects
    """
