# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 2077728154fbe14ee870e894e3289a02099bad4e29d3562bd37e3208476dd7c8

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import AutomationStatus, Config4, FunctionTypeEnum, GroupScope, RetentionObjectType, SpanScope, TraceScope


class Action(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action1(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config1(TypedDict):
    action: Action | Action1
    """
    The action to take when the automation rule is triggered
    """
    btql_filter: str
    """
    BTQL filter to identify rows for the automation rule
    """
    event_type: Literal["logs"]
    """
    The type of automation.
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    status: NotRequired[AutomationStatus]


class Credentials(TypedDict):
    external_id: str
    """
    The automation-specific external id component (auto-generated by default)
    """
    role_arn: str
    """
    The ARN of the IAM role to use
    """
    type: Literal["aws_iam"]


class Credentials1(TypedDict):
    service_account_email: str
    """
    The GCP service account email to impersonate
    """
    type: Literal["gcp_service_account"]


class ExportDefinition(TypedDict):
    type: Literal["log_traces"]


class ExportDefinition1(TypedDict):
    type: Literal["log_spans"]


class ExportDefinition2(TypedDict):
    btql_query: str
    """
    The BTQL query to export
    """
    type: Literal["btql_query"]


class Config3(TypedDict):
    batch_size: NotRequired[int | None]
    """
    The maximum number of result rows to write per async query batch
    """
    created_by_user_id: str
    """
    The user who submitted the async query
    """
    event_type: Literal["async_query"]
    """
    The type of automation.
    """
    format: Literal["jsonl"]
    """
    The materialized result format
    """
    object_id: str
    """
    The source object ID for the async query
    """
    object_type: Literal["project_logs", "experiment", "dataset", "playground_logs"]
    """
    The source object type for the async query
    """
    query: str
    """
    The SQL query to execute asynchronously
    """
    status: NotRequired[AutomationStatus]


class Action2(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action3(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config5(TypedDict):
    action: Action2 | Action3
    """
    The action to take when the automation rule is triggered
    """
    environment_filter: NotRequired[Sequence[str]]
    """
    Optional list of environment slugs to filter by
    """
    event_type: Literal["environment_update"]
    """
    The type of automation.
    """
    status: NotRequired[AutomationStatus]


class Action4(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action5(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config8(TypedDict):
    action: Action4 | Action5
    """
    The action to take when the automation rule is triggered
    """
    btql_filter: str
    """
    BTQL filter to identify rows for the automation rule
    """
    event_type: Literal["logs"]
    """
    The type of automation.
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    status: NotRequired[AutomationStatus]


class Credentials2(TypedDict):
    external_id: str
    """
    The automation-specific external id component (auto-generated by default)
    """
    role_arn: str
    """
    The ARN of the IAM role to use
    """
    type: Literal["aws_iam"]


class Credentials3(TypedDict):
    service_account_email: str
    """
    The GCP service account email to impersonate
    """
    type: Literal["gcp_service_account"]


class ExportDefinition3(TypedDict):
    type: Literal["log_traces"]


class ExportDefinition4(TypedDict):
    type: Literal["log_spans"]


class ExportDefinition5(TypedDict):
    btql_query: str
    """
    The BTQL query to export
    """
    type: Literal["btql_query"]


class Config10(TypedDict):
    batch_size: NotRequired[int | None]
    """
    The maximum number of result rows to write per async query batch
    """
    created_by_user_id: str
    """
    The user who submitted the async query
    """
    event_type: Literal["async_query"]
    """
    The type of automation.
    """
    format: Literal["jsonl"]
    """
    The materialized result format
    """
    object_id: str
    """
    The source object ID for the async query
    """
    object_type: Literal["project_logs", "experiment", "dataset", "playground_logs"]
    """
    The source object type for the async query
    """
    query: str
    """
    The SQL query to execute asynchronously
    """
    status: NotRequired[AutomationStatus]


class Action6(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action7(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config12(TypedDict):
    action: Action6 | Action7
    """
    The action to take when the automation rule is triggered
    """
    environment_filter: NotRequired[Sequence[str]]
    """
    Optional list of environment slugs to filter by
    """
    event_type: Literal["environment_update"]
    """
    The type of automation.
    """
    status: NotRequired[AutomationStatus]


class Action8(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action9(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config13(TypedDict):
    action: Action8 | Action9
    """
    The action to take when the automation rule is triggered
    """
    btql_filter: str
    """
    BTQL filter to identify rows for the automation rule
    """
    event_type: Literal["logs"]
    """
    The type of automation.
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    status: NotRequired[AutomationStatus]


class Credentials4(TypedDict):
    external_id: str
    """
    The automation-specific external id component (auto-generated by default)
    """
    role_arn: str
    """
    The ARN of the IAM role to use
    """
    type: Literal["aws_iam"]


class Credentials5(TypedDict):
    service_account_email: str
    """
    The GCP service account email to impersonate
    """
    type: Literal["gcp_service_account"]


class ExportDefinition6(TypedDict):
    type: Literal["log_traces"]


class ExportDefinition7(TypedDict):
    type: Literal["log_spans"]


class ExportDefinition8(TypedDict):
    btql_query: str
    """
    The BTQL query to export
    """
    type: Literal["btql_query"]


class Config15(TypedDict):
    batch_size: NotRequired[int | None]
    """
    The maximum number of result rows to write per async query batch
    """
    created_by_user_id: str
    """
    The user who submitted the async query
    """
    event_type: Literal["async_query"]
    """
    The type of automation.
    """
    format: Literal["jsonl"]
    """
    The materialized result format
    """
    object_id: str
    """
    The source object ID for the async query
    """
    object_type: Literal["project_logs", "experiment", "dataset", "playground_logs"]
    """
    The source object type for the async query
    """
    query: str
    """
    The SQL query to execute asynchronously
    """
    status: NotRequired[AutomationStatus]


class Action10(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Action11(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Config17(TypedDict):
    action: Action10 | Action11
    """
    The action to take when the automation rule is triggered
    """
    environment_filter: NotRequired[Sequence[str]]
    """
    Optional list of environment slugs to filter by
    """
    event_type: Literal["environment_update"]
    """
    The type of automation.
    """
    status: NotRequired[AutomationStatus]


ProjectAutomationIdParam: TypeAlias = str
"""
ProjectAutomation id
"""

ProjectAutomationName: TypeAlias = str
"""
Name of the project_automation to search for
"""

BackfillTimeRange = TypedDict(
    "BackfillTimeRange",
    {
        "from": str,
        "to": str,
    },
)


class FacetFunction1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class FacetFunction2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class FacetFunction3(TypedDict):
    pass


class FacetFunction4(FacetFunction1, FacetFunction3):
    pass


class FacetFunction5(FacetFunction2, FacetFunction3):
    pass


class FacetFunction6(FacetFunction1, FacetFunction3):
    pass


class FacetFunction7(FacetFunction2, FacetFunction3):
    pass


FacetFunction: TypeAlias = FacetFunction4 | FacetFunction5 | FacetFunction6 | FacetFunction7


class TopicAutomationDataScope1(TypedDict):
    type: Literal["project_logs"]


class TopicAutomationDataScope2(TypedDict):
    type: Literal["project_experiments"]


class TopicAutomationDataScope3(TypedDict):
    experiment_id: str
    type: Literal["experiment"]


TopicAutomationDataScope: TypeAlias = (
    TopicAutomationDataScope1 | TopicAutomationDataScope2 | TopicAutomationDataScope3 | None
)
"""
Optional data scope for topic automation.
"""

TopicAutomationFacetModel: TypeAlias = Literal["brain-facet-latest", "brain-facet-1", "brain-facet-2"] | None
"""
Optional facet model override for topic automation
"""


class TopicDigestAutomationConfig(TypedDict):
    action: Action11
    """
    The Slack action to take when the digest is sent
    """
    event_type: Literal["topic_digest"]
    """
    The type of automation.
    """
    scheduled_time_minutes_utc: int
    """
    Minutes after midnight UTC when the digest should be sent
    """
    status: NotRequired[AutomationStatus]
    topic_map_function_ids: NotRequired[Sequence[str]]
    """
    Optional topic map function IDs to include in the digest
    """
    window_seconds: NotRequired[int]
    """
    How much recent history to include in each digest
    """


class Function11(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class Function12(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class Function13(TypedDict):
    pass


class Function14(Function11, Function13):
    pass


class Function15(Function12, Function13):
    pass


class Function16(Function11, Function13):
    pass


class Function17(Function12, Function13):
    pass


Function1: TypeAlias = Function14 | Function15 | Function16 | Function17


class TopicMapFunctionAutomation(TypedDict):
    btql_filter: NotRequired[str | None]
    """
    Per-topic-map BTQL filter. For trace scope, a topic map runs when max(filter) over the trace is truthy. For span scope, it runs when the current span matches.
    """
    function: Function1


class Actions(TypedDict):
    formatting_prompt: NotRequired[str]
    """
    Instructions for Loop to format content sent to this destination
    """
    type: Literal["webhook"]
    """
    The type of action to take
    """
    url: str
    """
    The webhook URL to send the request to
    """


class Actions1(TypedDict):
    channel: str
    """
    The Slack channel ID to post to
    """
    formatting_prompt: NotRequired[str]
    """
    Publish a Slack mrkdwn digest.

    Include a complete "*Pattern outcomes*" section with one row for every selected Pattern from the run report, including created, updated, unchanged, failed, skipped, and newly inactive outcomes.

    Use this row format exactly:
    • <pattern_url|Pattern title> — `outcome`

    If a Pattern has no URL, use the plain title instead. Do not use GitHub Markdown tables or code-block tables, because links must remain clickable. Do not omit any selected Pattern. If there are no selected Patterns, say "No pattern outcomes."

    After the outcome list, include a "*Highlights*" section with one very short paragraph, 2-3 sentences maximum. Summarize what changed or what broadly stands out from this run. Do not introduce new claims beyond the run report.
    """
    message_template: NotRequired[str]
    """
    Custom message template for the alert
    """
    type: Literal["slack"]
    """
    The type of action to take
    """
    workspace_id: str
    """
    The Slack workspace ID to post to
    """


class Loop(TypedDict):
    agent_slug: str
    """
    The Loop agent to run
    """
    auto_approve_tools: NotRequired[Sequence[str]]
    """
    Write tools that may run without interactive approval
    """
    endpoint_name: NotRequired[str]
    harness: NotRequired[Literal["native", "codex", "claude-code"]]
    include_trigger_input: NotRequired[bool]
    """
    Whether to include the automation trigger payload as input
    """
    model: NotRequired[str]
    prompt: str
    """
    Instructions for the Loop agent
    """
    reasoning_effort: NotRequired[Literal["none", "minimal", "low", "medium", "high", "xhigh", "max"]]


class Output(TypedDict):
    type: Literal["scalar"]
    value_column: str
    """
    The numeric result column produced by the query
    """


class Calculation(TypedDict):
    btql_query: str
    """
    A project-scoped BTQL or SQL query without runtime-owned evaluation time bounds
    """
    output: Output
    type: Literal["btql"]


class Condition(TypedDict):
    operator: Literal["lt", "lte", "gt", "gte", "eq", "neq"]
    threshold: float
    type: Literal["threshold"]


class Policy(TypedDict):
    condition: Condition
    no_data_behavior: Literal["keep_last", "resolve", "alert"]
    """
    How the lifecycle changes when the calculation returns no data
    """
    notify_on_recovery: NotRequired[bool]
    """
    Whether to deliver actions when a firing automation recovers
    """
    pending_seconds: int
    """
    How long the condition must remain breached before firing
    """
    renotify_interval_seconds: NotRequired[int | None]
    """
    Optional reminder interval while the automation is firing
    """


class Threshold(TypedDict):
    calculation: Calculation
    """
    The calculation evaluated for each window
    """
    policy: Policy
    """
    The lifecycle policy applied to each calculation result
    """


class Schedule(TypedDict):
    evaluation_interval_seconds: int
    """
    How often the automation runs
    """
    type: Literal["interval"]


class Schedule1(TypedDict):
    cron_expression: str
    """
    A standard five-field cron expression (minute hour day-of-month month day-of-week) controlling when the automation runs
    """
    timezone: NotRequired[str | None]
    """
    IANA timezone used to interpret the cron expression (defaults to UTC)
    """
    type: Literal["cron"]


class Window(TypedDict):
    evaluation_delay_seconds: int
    """
    How far behind the present each evaluation window ends
    """
    schedule: Schedule | Schedule1
    """
    How often the windowed automation runs: at a fixed interval or on a cron schedule
    """
    window_seconds: int
    """
    How much recent data each scheduled run covers
    """


class WindowedAutomationConfig(TypedDict):
    actions: NotRequired[Sequence[Actions | Actions1]]
    """
    Delivery actions exposed to Loop as tools, or run directly when Loop is not configured
    """
    event_type: Literal["windowed"]
    """
    The type of automation.
    """
    loop: NotRequired[Loop]
    """
    Optional Loop agent to run for each triggered window
    """
    product_origin: NotRequired[Literal["patterns"] | None]
    """
    The product surface that created and manages the automation
    """
    status: NotRequired[AutomationStatus]
    threshold: NotRequired[Threshold]
    """
    Optional calculation and lifecycle policy that gate scheduled delivery
    """
    window: Window


class Config2(TypedDict):
    batch_size: NotRequired[float | None]
    """
    The number of rows to export in each batch
    """
    credentials: Credentials | Credentials1
    event_type: Literal["btql_export"]
    """
    The type of automation.
    """
    export_definition: ExportDefinition | ExportDefinition1 | ExportDefinition2
    """
    The definition of what to export
    """
    export_path: str
    """
    The path to export the results to. It should include the storage protocol and prefix, e.g. s3://bucket-name/path/to/export
    """
    format: Literal["jsonl", "parquet"]
    """
    The format to export the results in
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    scope: NotRequired[SpanScope | TraceScope | GroupScope | None]
    """
    Execution scope for export automation. Defaults to span-level execution.
    """
    status: NotRequired[AutomationStatus]


class Config9(TypedDict):
    batch_size: NotRequired[float | None]
    """
    The number of rows to export in each batch
    """
    credentials: Credentials2 | Credentials3
    event_type: Literal["btql_export"]
    """
    The type of automation.
    """
    export_definition: ExportDefinition3 | ExportDefinition4 | ExportDefinition5
    """
    The definition of what to export
    """
    export_path: str
    """
    The path to export the results to. It should include the storage protocol and prefix, e.g. s3://bucket-name/path/to/export
    """
    format: Literal["jsonl", "parquet"]
    """
    The format to export the results in
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    scope: NotRequired[SpanScope | TraceScope | GroupScope | None]
    """
    Execution scope for export automation. Defaults to span-level execution.
    """
    status: NotRequired[AutomationStatus]


class Config11(TypedDict):
    event_type: Literal["retention"]
    """
    The type of automation.
    """
    object_type: RetentionObjectType
    retention_days: int
    """
    The number of days to retain the object
    """


class Config14(TypedDict):
    batch_size: NotRequired[float | None]
    """
    The number of rows to export in each batch
    """
    credentials: Credentials4 | Credentials5
    event_type: Literal["btql_export"]
    """
    The type of automation.
    """
    export_definition: ExportDefinition6 | ExportDefinition7 | ExportDefinition8
    """
    The definition of what to export
    """
    export_path: str
    """
    The path to export the results to. It should include the storage protocol and prefix, e.g. s3://bucket-name/path/to/export
    """
    format: Literal["jsonl", "parquet"]
    """
    The format to export the results in
    """
    interval_seconds: float
    """
    Perform the triggered action at most once in this interval of seconds
    """
    scope: NotRequired[SpanScope | TraceScope | GroupScope | None]
    """
    Execution scope for export automation. Defaults to span-level execution.
    """
    status: NotRequired[AutomationStatus]


class Config16(TypedDict):
    event_type: Literal["retention"]
    """
    The type of automation.
    """
    object_type: RetentionObjectType
    retention_days: int
    """
    The number of days to retain the object
    """


class TopicAutomationConfig(TypedDict):
    backfill_time_range: NotRequired[str | BackfillTimeRange | None]
    """
    Topic window used for classification coverage and initial backfill.
    """
    btql_filter: NotRequired[str | None]
    """
    Optional BTQL filter applied before topic automation.
    """
    data_scope: NotRequired[TopicAutomationDataScope]
    event_type: Literal["topic"]
    """
    The type of automation.
    """
    facet_functions: Sequence[FacetFunction]
    """
    Facet functions used by the topic automation
    """
    facet_model: NotRequired[TopicAutomationFacetModel | None]
    relabel_overlap_seconds: NotRequired[float | None]
    """
    How much recent history to relabel after a new topic map version becomes active
    """
    rerun_seconds: NotRequired[float | None]
    """
    How often to recompute topic maps
    """
    sampling_rate: float
    """
    The sampling rate for topic automation
    """
    scope: NotRequired[SpanScope | TraceScope | GroupScope | None]
    """
    Execution scope for topic automation.
    """
    status: NotRequired[AutomationStatus]
    topic_map_functions: Sequence[TopicMapFunctionAutomation]
    """
    Topic map functions with optional per-topic-map filters
    """


class CreateProjectAutomation(TypedDict):
    config: (
        Config1
        | Config2
        | Config3
        | Config4
        | Config5
        | WindowedAutomationConfig
        | TopicAutomationConfig
        | TopicDigestAutomationConfig
    )
    """
    The configuration for the automation rule
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    name: str
    """
    Name of the project automation
    """
    project_id: str
    """
    Unique identifier for the project that the project automation belongs under
    """


class PatchProjectAutomation(TypedDict):
    config: NotRequired[
        Config8
        | Config9
        | Config10
        | Config11
        | Config12
        | WindowedAutomationConfig
        | TopicAutomationConfig
        | TopicDigestAutomationConfig
        | Any
    ]
    """
    The configuration for the automation rule
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    name: NotRequired[str | None]
    """
    Name of the project automation
    """


class ProjectAutomation(TypedDict):
    config: (
        Config13
        | Config14
        | Config15
        | Config16
        | Config17
        | WindowedAutomationConfig
        | TopicAutomationConfig
        | TopicDigestAutomationConfig
    )
    """
    The configuration for the automation rule
    """
    created: NotRequired[str | None]
    """
    Date of project automation creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the project automation
    """
    id: str
    """
    Unique identifier for the project automation
    """
    name: str
    """
    Name of the project automation
    """
    project_id: str
    """
    Unique identifier for the project that the project automation belongs under
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project automation
    """


class GetProjectAutomationResponse(TypedDict):
    objects: Sequence[ProjectAutomation]
    """
    A list of project_automation objects
    """
