# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: df42dc8e0c114ae0d22a847726c364f9b37f9f99778a6a9d34d427f288f93354

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import FunctionTypeEnum


class CreateProject(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    name: str
    """
    Name of the project
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the project belongs in.
    """


class NullableSavedFunctionId1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class NullableSavedFunctionId2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


NullableSavedFunctionId: TypeAlias = NullableSavedFunctionId1 | NullableSavedFunctionId2 | None
"""
Default preprocessor for this project. When set, functions that use preprocessors will use this instead of their built-in default.
"""

ProjectIdParam: TypeAlias = str
"""
Project id
"""


class RemoteEvalSource(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    url: str


class SpanFieldOrderItem(TypedDict):
    column_id: str
    layout: NotRequired[Literal["full"] | Literal["two_column"] | None]
    object_type: str
    position: str


class ProjectSettings(TypedDict):
    baseline_experiment_id: NotRequired[str | None]
    """
    The id of the experiment to use as the default baseline for comparisons
    """
    blind_reviews: NotRequired[bool | None]
    """
    If true, hide peer review scores, comments, and aggregate results from reviewers without project update permissions until they submit their own review.
    """
    comparison_key: NotRequired[str | None]
    """
    The key used to join two experiments (defaults to `input`)
    """
    default_preprocessor: NotRequired[NullableSavedFunctionId]
    disable_realtime_queries: NotRequired[bool | None]
    """
    If true, disable real-time queries for this project. This can improve query performance for high-volume logs.
    """
    monitor_charts_use_metrics_start: NotRequired[bool | None]
    """
    If true, use metrics.start rather than created for monitor chart time bucket dimensions.
    """
    remote_eval_sources: NotRequired[Sequence[RemoteEvalSource] | None]
    """
    The remote eval sources to use for the project
    """
    spanFieldOrder: NotRequired[Sequence[SpanFieldOrderItem] | None]
    """
    The order of the fields to display in the trace view
    """


class PatchProject(TypedDict):
    description: NotRequired[str | None]
    name: NotRequired[str | None]
    """
    Name of the project
    """
    settings: NotRequired[ProjectSettings]
    user_id: NotRequired[str | None]


class Project(TypedDict):
    created: NotRequired[str | None]
    """
    Date of project creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of project deletion, or null if the project is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the project
    """
    id: str
    """
    Unique identifier for the project
    """
    name: str
    """
    Name of the project
    """
    org_id: str
    """
    Unique id for the organization that the project belongs under
    """
    settings: NotRequired[ProjectSettings | None]
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the project
    """


class GetProjectResponse(TypedDict):
    objects: Sequence[Project]
    """
    A list of project objects
    """
