# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 8131225200448e09109b065a125dc7307509cb43906ef1de772f600610107ac2

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import AutomationStatus, FunctionTypeEnum, GroupScope, SpanScope, TraceScope


class Scorer1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class Scorer2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class Scorer3(TypedDict):
    pass


class Scorer4(Scorer1, Scorer3):
    pass


class Scorer5(Scorer2, Scorer3):
    pass


class Scorer6(Scorer1, Scorer3):
    pass


class Scorer7(Scorer2, Scorer3):
    pass


Scorer: TypeAlias = Scorer4 | Scorer5 | Scorer6 | Scorer7


class ProjectScoreCategory(TypedDict):
    name: str
    """
    Name of the category
    """
    value: float
    """
    Numerical value of the category. Must be between 0 and 1, inclusive
    """


class When(TypedDict):
    clauses: NotRequired[Sequence[str] | None]
    subspan_clauses: NotRequired[Sequence[str] | None]
    trace_clauses: NotRequired[Sequence[str] | None]


class ProjectScoreCondition(TypedDict):
    behavior: NotRequired[Literal["hidden"]]
    when: When


class Visibility(TypedDict):
    groups: NotRequired[Sequence[str] | None]
    users: NotRequired[Sequence[str] | None]


ProjectScoreIdParam: TypeAlias = str
"""
ProjectScore id
"""

ProjectScoreName: TypeAlias = str
"""
Name of the project_score to search for
"""

ProjectScoreType: TypeAlias = Literal["slider", "categorical", "weighted", "minimum", "maximum", "online", "free-form"]
"""
The type of the configured score
"""


class OnlineScoreConfig(TypedDict):
    apply_to_root_span: NotRequired[bool | None]
    """
    Whether to trigger online scoring on the root span of each trace. Only applies when scope is 'span' or unset.
    """
    apply_to_span_names: NotRequired[Sequence[str] | None]
    """
    Trigger online scoring on any spans with a name in this list. Only applies when scope is 'span' or unset.
    """
    btql_filter: NotRequired[str | None]
    """
    Filter logs using BTQL
    """
    sampling_rate: float
    """
    The sampling rate for online scoring
    """
    scope: NotRequired[SpanScope | TraceScope | GroupScope | None]
    """
    The scope at which to run the functions. Defaults to span-level execution.
    """
    scorers: Sequence[Scorer]
    """
    The list of functions to run for online scoring. Can include scorers, facets, or other function types.
    """
    skip_logging: NotRequired[bool | None]
    """
    Whether to skip adding scorer spans when computing scores
    """
    status: NotRequired[AutomationStatus]


ProjectScoreCategories: TypeAlias = Sequence[ProjectScoreCategory] | Mapping[str, float] | Sequence[str] | None


class ProjectScoreConfig(TypedDict):
    condition: NotRequired[ProjectScoreCondition | None]
    destination: NotRequired[str | None]
    multi_select: NotRequired[bool | None]
    object_types: NotRequired[Sequence[Literal["project_logs", "dataset", "experiment"]] | None]
    online: NotRequired[OnlineScoreConfig | None]
    visibility: NotRequired[Visibility | None]


class CreateProjectScore(TypedDict):
    categories: NotRequired[ProjectScoreCategories]
    config: NotRequired[ProjectScoreConfig | None]
    description: NotRequired[str | None]
    """
    Textual description of the project score
    """
    name: str
    """
    Name of the project score
    """
    project_id: str
    """
    Unique identifier for the project that the project score belongs under
    """
    score_type: ProjectScoreType


class PatchProjectScore(TypedDict):
    categories: NotRequired[ProjectScoreCategories]
    config: NotRequired[ProjectScoreConfig | None]
    description: NotRequired[str | None]
    """
    Textual description of the project score
    """
    name: NotRequired[str | None]
    """
    Name of the project score
    """
    score_type: NotRequired[ProjectScoreType | None]


class ProjectScore(TypedDict):
    categories: NotRequired[ProjectScoreCategories]
    config: NotRequired[ProjectScoreConfig | None]
    created: NotRequired[str | None]
    """
    Date of project score creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the project score
    """
    id: str
    """
    Unique identifier for the project score
    """
    name: str
    """
    Name of the project score
    """
    position: NotRequired[str | None]
    """
    An optional LexoRank-based string that sets the sort position for the score in the UI
    """
    project_id: str
    """
    Unique identifier for the project that the project score belongs under
    """
    score_type: ProjectScoreType
    user_id: str


class GetProjectScoreResponse(TypedDict):
    objects: Sequence[ProjectScore]
    """
    A list of project_score objects
    """
