# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 936b39c6f2052c11472f458accba4692d8fa35225bf95fd9efe4486d6ba3564c

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateProjectTag(TypedDict):
    color: NotRequired[str | None]
    """
    Color of the tag for the UI
    """
    description: NotRequired[str | None]
    """
    Textual description of the project tag
    """
    name: str
    """
    Name of the project tag
    """
    project_id: str
    """
    Unique identifier for the project that the project tag belongs under
    """


class PatchProjectTag(TypedDict):
    color: NotRequired[str | None]
    """
    Color of the tag for the UI
    """
    description: NotRequired[str | None]
    """
    Textual description of the project tag
    """
    name: NotRequired[str | None]
    """
    Name of the project tag
    """


class ProjectTag(TypedDict):
    color: NotRequired[str | None]
    """
    Color of the tag for the UI
    """
    created: NotRequired[str | None]
    """
    Date of project tag creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the project tag
    """
    id: str
    """
    Unique identifier for the project tag
    """
    name: str
    """
    Name of the project tag
    """
    position: NotRequired[str | None]
    """
    An optional LexoRank-based string that sets the sort position for the tag in the UI
    """
    project_id: str
    """
    Unique identifier for the project that the project tag belongs under
    """
    user_id: str


ProjectTagIdParam: TypeAlias = str
"""
ProjectTag id
"""

ProjectTagName: TypeAlias = str
"""
Name of the project_tag to search for
"""


class GetProjectTagResponse(TypedDict):
    objects: Sequence[ProjectTag]
    """
    A list of project_tag objects
    """
