# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 0ec7d11315d85b755a496e3e33ffe15ed9b3600a66bc2be20906b0ba311c76bc

from typing import Any, Literal, TypeAlias, TypedDict
from typing_extensions import NotRequired
from collections.abc import Mapping, Sequence

from .common import FunctionTypeEnumNullish, PromptDataNullish

PromptIdParam: TypeAlias = str
"""
Prompt id
"""

PromptName: TypeAlias = str
"""
Name of the prompt to search for
"""


class CreatePrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    name: str
    """
    Name of the prompt
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class PatchPrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    name: NotRequired[str | None]
    """
    Name of the prompt
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: NotRequired[str | None]
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class Prompt(TypedDict):
    _xact_id: str
    """
    The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the prompt (see the `version` parameter)
    """
    created: NotRequired[str | None]
    """
    Date of prompt creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    id: str
    """
    Unique identifier for the prompt
    """
    log_id: Literal["p"]
    """
    A literal 'p' which identifies the object as a project prompt
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the prompt
    """
    name: str
    """
    Name of the prompt
    """
    org_id: str
    """
    Unique identifier for the organization
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class GetPromptResponse(TypedDict):
    objects: Sequence[Prompt]
    """
    A list of prompt objects
    """
