# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 78b54a29790fb3e71240709027007e2ff3c68c0348a8c415c79c340de5432eb6

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import FunctionTypeEnumNullish, PromptDataNullish

PromptIdParam: TypeAlias = str
"""
Prompt id
"""

PromptName: TypeAlias = str
"""
Name of the prompt to search for
"""


class CreatePrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    environment_slugs: NotRequired[Sequence[str] | None]
    """
    A list of environment slugs to assign the prompt to. Each slug must reference an existing environment; if any slug does not exist, the entire request fails and the prompt is not created.
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    name: str
    """
    Name of the prompt
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class PatchPrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    name: NotRequired[str | None]
    """
    Name of the prompt
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: NotRequired[str | None]
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class Prompt(TypedDict):
    _xact_id: str
    """
    The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the prompt (see the `version` parameter)
    """
    created: NotRequired[str | None]
    """
    Date of prompt creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    id: str
    """
    Unique identifier for the prompt
    """
    log_id: Literal["p"]
    """
    A literal 'p' which identifies the object as a project prompt
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the prompt
    """
    name: str
    """
    Name of the prompt
    """
    org_id: str
    """
    Unique identifier for the organization
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class GetPromptResponse(TypedDict):
    objects: Sequence[Prompt]
    """
    A list of prompt objects
    """
