# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: bacb6ce9b0a44df81cd41c75e92a79000c50c826bee226218b541ea94dd73636

from typing import Any, Literal, TypeAlias, TypedDict
from typing_extensions import NotRequired
from collections.abc import Mapping, Sequence

from .common import FunctionTypeEnum


class ChatCompletionContentPartFileFile(TypedDict):
    file_data: NotRequired[str]
    file_id: NotRequired[str]
    filename: NotRequired[str]


class CacheControl(TypedDict):
    ttl: NotRequired[Literal["5m", "1h"]]
    type: Literal["ephemeral"]


class ChatCompletionContentPartFileWithTitle(TypedDict):
    cache_control: NotRequired[CacheControl]
    file: ChatCompletionContentPartFileFile
    type: Literal["file"]


class ImageUrl(TypedDict):
    detail: NotRequired[Literal["auto"] | Literal["low"] | Literal["high"]]
    url: str


class ChatCompletionContentPartImageWithTitle(TypedDict):
    cache_control: NotRequired[CacheControl]
    image_url: ImageUrl
    type: Literal["image_url"]


class ChatCompletionContentPartText(TypedDict):
    cache_control: NotRequired[CacheControl]
    text: NotRequired[str]
    type: Literal["text"]


class ChatCompletionContentPartTextWithTitle(TypedDict):
    cache_control: NotRequired[CacheControl]
    text: NotRequired[str]
    type: Literal["text"]


class ChatCompletionMessageParam1(TypedDict):
    content: NotRequired[str | Sequence[ChatCompletionContentPartText]]
    name: NotRequired[str]
    role: Literal["system"]


class FunctionCall(TypedDict):
    arguments: str
    name: str


class ChatCompletionMessageParam4(TypedDict):
    content: NotRequired[str | Sequence[ChatCompletionContentPartText]]
    role: Literal["tool"]
    tool_call_id: NotRequired[str]


class ChatCompletionMessageParam5(TypedDict):
    content: str | None
    name: str
    role: Literal["function"]


class ChatCompletionMessageParam6(TypedDict):
    content: NotRequired[str | Sequence[ChatCompletionContentPartText]]
    name: NotRequired[str]
    role: Literal["developer"]


class ChatCompletionMessageParam7(TypedDict):
    content: NotRequired[str | None]
    role: Literal["model"]


class ChatCompletionMessageReasoning(TypedDict):
    content: NotRequired[str | None]
    id: NotRequired[str | None]


class Function(TypedDict):
    arguments: str
    name: str


class ChatCompletionMessageToolCall(TypedDict):
    function: Function
    id: str
    type: Literal["function"]


FunctionTypeEnumNullish: TypeAlias = (
    Literal[
        "llm",
        "scorer",
        "task",
        "tool",
        "custom_view",
        "preprocessor",
        "facet",
        "classifier",
        "tag",
        "parameters",
        "sandbox",
    ]
    | None
)


class FunctionCall1(TypedDict):
    name: str


class Function1(TypedDict):
    name: str


class ToolChoice(TypedDict):
    function: Function1
    type: Literal["function"]


class ModelParams2(TypedDict):
    max_tokens: float
    max_tokens_to_sample: NotRequired[float]
    """
    This is a legacy parameter that should not be used.
    """
    reasoning_budget: NotRequired[float]
    reasoning_enabled: NotRequired[bool]
    stop_sequences: NotRequired[Sequence[str]]
    temperature: float
    top_k: NotRequired[float]
    top_p: NotRequired[float]
    use_cache: NotRequired[bool]


class ModelParams3(TypedDict):
    maxOutputTokens: NotRequired[float]
    reasoning_budget: NotRequired[float]
    reasoning_enabled: NotRequired[bool]
    temperature: NotRequired[float]
    topK: NotRequired[float]
    topP: NotRequired[float]
    use_cache: NotRequired[bool]


class ModelParams4(TypedDict):
    reasoning_budget: NotRequired[float]
    reasoning_enabled: NotRequired[bool]
    temperature: NotRequired[float]
    topK: NotRequired[float]
    use_cache: NotRequired[bool]


class ModelParams5(TypedDict):
    reasoning_budget: NotRequired[float]
    reasoning_enabled: NotRequired[bool]
    use_cache: NotRequired[bool]


class PreprocessorId1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class PreprocessorId2(TypedDict):
    function_type: NotRequired[Literal["preprocessor"]]
    """
    The type of global function. Defaults to 'preprocessor'.
    """
    name: str
    type: Literal["global"]


class PreprocessorId3(TypedDict):
    code: str
    """
    The complete JavaScript preprocessor implementation, including its handler.
    """
    type: Literal["inline"]


PreprocessorId: TypeAlias = PreprocessorId1 | PreprocessorId2 | PreprocessorId3 | None
"""
For prompt-backed functions: the saved, global, or inline preprocessor to use for trace template variables. Set to null to disable preprocessing. If omitted, the traced project's default preprocessor will be used, falling back to the global 'thread' preprocessor.
"""


class PromptBlockDataNullish2(TypedDict):
    content: str
    type: Literal["completion"]


class Mcp(TypedDict):
    enabled_tools: NotRequired[Sequence[str] | None]
    """
    If omitted, all tools are enabled
    """
    id: str
    is_disabled: NotRequired[bool]
    type: Literal["id"]


class Mcp1(TypedDict):
    enabled_tools: NotRequired[Sequence[str] | None]
    """
    If omitted, all tools are enabled
    """
    is_disabled: NotRequired[bool]
    type: Literal["url"]
    url: str


class Origin(TypedDict):
    project_id: NotRequired[str]
    prompt_id: NotRequired[str]
    prompt_version: NotRequired[str]


class ToolFunction1(TypedDict):
    id: str
    type: Literal["function"]
    version: NotRequired[str]
    """
    The version of the function
    """


class ToolFunction2(TypedDict):
    function_type: NotRequired[FunctionTypeEnum]
    name: str
    type: Literal["global"]


class ToolFunction3(TypedDict):
    pass


class ToolFunction4(ToolFunction1, ToolFunction3):
    pass


class ToolFunction5(ToolFunction2, ToolFunction3):
    pass


class ToolFunction6(ToolFunction1, ToolFunction3):
    pass


class ToolFunction7(ToolFunction2, ToolFunction3):
    pass


ToolFunction: TypeAlias = ToolFunction4 | ToolFunction5 | ToolFunction6 | ToolFunction7

PromptEnvironment: TypeAlias = str
"""
Filter by environment slug. Cannot be used together with `version`.

For `GET /v1/prompt`, environment resolution currently requires the request to match a single prompt. If multiple prompts match, the endpoint returns `400` (for example when `limit=1` is not set). Use `limit=1` or other filters (for example `slug`, `project_id`) to narrow results.
"""

PromptIdParam: TypeAlias = str
"""
Prompt id
"""

PromptName: TypeAlias = str
"""
Name of the prompt to search for
"""


class PromptParserNullish(TypedDict):
    allow_no_match: NotRequired[bool]
    """
    If true, adds a 'No match' option. When selected, no tag is deposited.
    """
    allow_skip: NotRequired[bool]
    """
    If true, adds a 'Skip' option. When selected, the scorer returns null.
    """
    choice: NotRequired[Sequence[str]]
    """
    List of valid choices without score mapping. Used by classifiers that deposit output to tags.
    """
    choice_scores: NotRequired[Mapping[str, float]]
    """
    Map of choices to scores (0-1). Used by scorers.
    """
    type: Literal["llm_classifier"]
    use_cot: bool


PromptVersion: TypeAlias = str
"""
Retrieve prompt at a specific version.

The version id can either be a transaction id (e.g. '1000192656880881099') or a version identifier (e.g. '81cd05ee665fdfb3').
"""


class ResponseFormatJsonSchema(TypedDict):
    description: NotRequired[str]
    name: str
    schema: NotRequired[Mapping[str, Any] | str]
    strict: NotRequired[bool | None]


class ResponseFormatNullish1(TypedDict):
    type: Literal["json_object"]


class ResponseFormatNullish2(TypedDict):
    json_schema: ResponseFormatJsonSchema
    type: Literal["json_schema"]


class ResponseFormatNullish3(TypedDict):
    type: Literal["text"]


ResponseFormatNullish: TypeAlias = ResponseFormatNullish1 | ResponseFormatNullish2 | ResponseFormatNullish3 | None

Slug: TypeAlias = str
"""
Retrieve prompt with a specific slug
"""

ChatCompletionContentPart: TypeAlias = (
    ChatCompletionContentPartTextWithTitle
    | ChatCompletionContentPartImageWithTitle
    | ChatCompletionContentPartFileWithTitle
)


class ChatCompletionMessageParam2(TypedDict):
    content: NotRequired[str | Sequence[ChatCompletionContentPart]]
    name: NotRequired[str]
    role: Literal["user"]


class ChatCompletionMessageParam3(TypedDict):
    content: NotRequired[str | Sequence[ChatCompletionContentPartText] | None]
    function_call: NotRequired[FunctionCall | None]
    name: NotRequired[str | None]
    reasoning: NotRequired[Sequence[ChatCompletionMessageReasoning] | None]
    reasoning_signature: NotRequired[str | None]
    role: Literal["assistant"]
    tool_calls: NotRequired[Sequence[ChatCompletionMessageToolCall] | None]


ChatCompletionMessageParam: TypeAlias = (
    ChatCompletionMessageParam1
    | ChatCompletionMessageParam2
    | ChatCompletionMessageParam3
    | ChatCompletionMessageParam4
    | ChatCompletionMessageParam5
    | ChatCompletionMessageParam6
    | ChatCompletionMessageParam7
)


class ModelParams1(TypedDict):
    frequency_penalty: NotRequired[float]
    function_call: NotRequired[Literal["auto"] | Literal["none"] | FunctionCall1]
    max_completion_tokens: NotRequired[float]
    """
    The successor to max_tokens
    """
    max_tokens: NotRequired[float]
    n: NotRequired[float]
    presence_penalty: NotRequired[float]
    reasoning_budget: NotRequired[float]
    reasoning_effort: NotRequired[Literal["none", "minimal", "low", "medium", "high"]]
    reasoning_enabled: NotRequired[bool]
    response_format: NotRequired[ResponseFormatNullish]
    stop: NotRequired[Sequence[str]]
    temperature: NotRequired[float]
    tool_choice: NotRequired[Literal["auto"] | Literal["none"] | Literal["required"] | ToolChoice]
    top_p: NotRequired[float]
    use_cache: NotRequired[bool]
    verbosity: NotRequired[Literal["low", "medium", "high"]]


ModelParams: TypeAlias = ModelParams1 | ModelParams2 | ModelParams3 | ModelParams4 | ModelParams5


class PromptBlockDataNullish1(TypedDict):
    messages: Sequence[ChatCompletionMessageParam]
    tools: NotRequired[str]
    type: Literal["chat"]


PromptBlockDataNullish: TypeAlias = PromptBlockDataNullish1 | PromptBlockDataNullish2 | None


class PromptOptionsNullish(TypedDict):
    endpoint_name: NotRequired[str | None]
    model: NotRequired[str]
    params: NotRequired[ModelParams]
    position: NotRequired[str]


class PromptDataNullish(TypedDict):
    mcp: NotRequired[Mapping[str, Mcp | Mcp1] | None]
    options: NotRequired[PromptOptionsNullish | None]
    origin: NotRequired[Origin | None]
    parser: NotRequired[PromptParserNullish | None]
    preprocessor: NotRequired[PreprocessorId]
    prompt: NotRequired[PromptBlockDataNullish]
    template_format: NotRequired[Literal["mustache", "nunjucks", "none"] | None]
    tool_functions: NotRequired[Sequence[ToolFunction] | None]


class CreatePrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    name: str
    """
    Name of the prompt
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class PatchPrompt(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    name: NotRequired[str | None]
    """
    Name of the prompt
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: NotRequired[str | None]
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class Prompt(TypedDict):
    _xact_id: str
    """
    The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the prompt (see the `version` parameter)
    """
    created: NotRequired[str | None]
    """
    Date of prompt creation
    """
    description: NotRequired[str | None]
    """
    Textual description of the prompt
    """
    function_type: NotRequired[FunctionTypeEnumNullish | None]
    id: str
    """
    Unique identifier for the prompt
    """
    log_id: Literal["p"]
    """
    A literal 'p' which identifies the object as a project prompt
    """
    metadata: NotRequired[Mapping[str, Any] | None]
    """
    User-controlled metadata about the prompt
    """
    name: str
    """
    Name of the prompt
    """
    org_id: str
    """
    Unique identifier for the organization
    """
    project_id: str
    """
    Unique identifier for the project that the prompt belongs under
    """
    prompt_data: NotRequired[PromptDataNullish | None]
    slug: str
    """
    Unique identifier for the prompt
    """
    tags: NotRequired[Sequence[str] | None]
    """
    A list of tags for the prompt
    """


class GetPromptResponse(TypedDict):
    objects: Sequence[Prompt]
    """
    A list of prompt objects
    """
