# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: a978d2137e33b725ba9fc1dc796c2fd8fd8b5be3f9d588371f5acab5e0f97b2f

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import AclObjectType, Permission


class MemberPermission(TypedDict):
    permission: Permission
    restrict_object_type: NotRequired[AclObjectType | None]


class Role(TypedDict):
    created: NotRequired[str | None]
    """
    Date of role creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of role deletion, or null if the role is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the role
    """
    id: str
    """
    Unique identifier for the role
    """
    member_permissions: NotRequired[Sequence[MemberPermission] | None]
    """
    (permission, restrict_object_type) tuples which belong to this role
    """
    member_roles: NotRequired[Sequence[str] | None]
    """
    Ids of the roles this role inherits from

    An inheriting role has all the permissions contained in its member roles, as well as all of their inherited permissions
    """
    name: str
    """
    Name of the role
    """
    org_id: NotRequired[str | None]
    """
    Unique id for the organization that the role belongs under

    A null org_id indicates a system role, which may be assigned to anybody and inherited by any other role, but cannot be edited.

    It is forbidden to change the org after creating a role
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the role
    """


RoleIdParam: TypeAlias = str
"""
Role id
"""

RoleName: TypeAlias = str
"""
Name of the role to search for
"""


class CreateRole(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the role
    """
    member_permissions: NotRequired[Sequence[MemberPermission] | None]
    """
    (permission, restrict_object_type) tuples which belong to this role
    """
    member_roles: NotRequired[Sequence[str] | None]
    """
    Ids of the roles this role inherits from

    An inheriting role has all the permissions contained in its member roles, as well as all of their inherited permissions
    """
    name: str
    """
    Name of the role
    """
    org_name: NotRequired[str | None]
    """
    For nearly all users, this parameter should be unnecessary. But in the rare case that your API key belongs to multiple organizations, you may specify the name of the organization the role belongs in.
    """


class GetRoleResponse(TypedDict):
    objects: Sequence[Role]
    """
    A list of role objects
    """


class AddMemberPermission(TypedDict):
    permission: Permission
    restrict_object_type: NotRequired[AclObjectType | None]


class RemoveMemberPermission(TypedDict):
    permission: Permission
    restrict_object_type: NotRequired[AclObjectType | None]


class PatchRole(TypedDict):
    add_member_permissions: NotRequired[Sequence[AddMemberPermission] | None]
    """
    A list of permissions to add to the role
    """
    add_member_roles: NotRequired[Sequence[str] | None]
    """
    A list of role IDs to add to the role's inheriting-from set
    """
    description: NotRequired[str | None]
    """
    Textual description of the role
    """
    name: NotRequired[str | None]
    """
    Name of the role
    """
    remove_member_permissions: NotRequired[Sequence[RemoveMemberPermission] | None]
    """
    A list of permissions to remove from the role
    """
    remove_member_roles: NotRequired[Sequence[str] | None]
    """
    A list of role IDs to remove from the role's inheriting-from set
    """
