# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: d74398cc90ee2110cbc8b873528850dceb97f7ed78f9a57df08568c4337d1e35

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateServiceTokenOutput(TypedDict):
    created: NotRequired[str | None]
    """
    Date of service token creation
    """
    expires_at: NotRequired[str | None]
    """
    Date and time at which the service token expires. If null, the token never expires.
    """
    id: str
    """
    Unique identifier for the service token
    """
    key: str
    """
    The raw service token. It will only be exposed this one time
    """
    name: str
    """
    Name of the service token
    """
    org_id: NotRequired[str | None]
    """
    Unique identifier for the organization
    """
    preview_name: str
    service_account_email: NotRequired[str | None]
    """
    The service account email (not routable)
    """
    service_account_id: NotRequired[str | None]
    """
    Unique identifier for the service token
    """
    service_account_name: NotRequired[str | None]
    """
    The service account name
    """


class DeleteServiceToken(TypedDict):
    id: str
    """
    Unique identifier for the service token.
    """


class ServiceToken(TypedDict):
    created: NotRequired[str | None]
    """
    Date of service token creation
    """
    expires_at: NotRequired[str | None]
    """
    Date and time at which the service token expires. If null, the token never expires.
    """
    id: str
    """
    Unique identifier for the service token
    """
    name: str
    """
    Name of the service token
    """
    org_id: NotRequired[str | None]
    """
    Unique identifier for the organization
    """
    preview_name: str
    service_account_email: NotRequired[str | None]
    """
    The service account email (not routable)
    """
    service_account_id: NotRequired[str | None]
    """
    Unique identifier for the service token
    """
    service_account_name: NotRequired[str | None]
    """
    The service account name
    """


ServiceTokenIdParam: TypeAlias = str
"""
ServiceToken id
"""

ServiceTokenName: TypeAlias = str
"""
Name of the service_token to search for
"""


class GetServiceTokenResponse(TypedDict):
    objects: Sequence[ServiceToken]
    """
    A list of service_token objects
    """
