# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 66eed24b98cd0f5609c9f524230a61497f7fd77d
# OpenAPI spec SHA-256: 877ab1fd2a22c407af1975a2f880170fb5dc2d31f550c1ce611b407037e4f221
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 2de5bfdfec105e4d78666d0370d71a7164e583f0403fde7e3f376889f8734952

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class CreateSpanIFrame(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the span iframe
    """
    name: str
    """
    Name of the span iframe
    """
    post_message: NotRequired[bool | None]
    """
    Whether to post messages to the iframe containing the span's data. This is useful when you want to render more data than fits in the URL.
    """
    project_id: str
    """
    Unique identifier for the project that the span iframe belongs under
    """
    url: str
    """
    URL to embed the project viewer in an iframe
    """


class PatchSpanIFrame(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the span iframe
    """
    name: NotRequired[str | None]
    """
    Name of the span iframe
    """
    post_message: NotRequired[bool | None]
    """
    Whether to post messages to the iframe containing the span's data. This is useful when you want to render more data than fits in the URL.
    """
    url: NotRequired[str | None]
    """
    URL to embed the project viewer in an iframe
    """


class SpanIFrame(TypedDict):
    created: NotRequired[str | None]
    """
    Date of span iframe creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of span iframe deletion, or null if the span iframe is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the span iframe
    """
    id: str
    """
    Unique identifier for the span iframe
    """
    name: str
    """
    Name of the span iframe
    """
    post_message: NotRequired[bool | None]
    """
    Whether to post messages to the iframe containing the span's data. This is useful when you want to render more data than fits in the URL.
    """
    project_id: str
    """
    Unique identifier for the project that the span iframe belongs under
    """
    url: str
    """
    URL to embed the project viewer in an iframe
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the span iframe
    """


SpanIframeIdParam: TypeAlias = str
"""
SpanIframe id
"""

SpanIframeName: TypeAlias = str
"""
Name of the span_iframe to search for
"""


class GetSpanIframeResponse(TypedDict):
    objects: Sequence[SpanIFrame]
    """
    A list of span_iframe objects
    """
