# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 66eed24b98cd0f5609c9f524230a61497f7fd77d
# OpenAPI spec SHA-256: 877ab1fd2a22c407af1975a2f880170fb5dc2d31f550c1ce611b407037e4f221
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 5623dc4e05cb6d3e728dcd6104d6c9dd880cf2ffea4d7f3725d34d997f242b5d

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence


class User(TypedDict):
    avatar_url: NotRequired[str | None]
    """
    URL of the user's Avatar image
    """
    created: NotRequired[str | None]
    """
    Date of user creation
    """
    email: NotRequired[str | None]
    """
    The user's email
    """
    family_name: NotRequired[str | None]
    """
    Family name of the user
    """
    given_name: NotRequired[str | None]
    """
    Given name of the user
    """
    id: str
    """
    Unique identifier for the user
    """


UserEmail: TypeAlias = str | Sequence[str]
"""
Email of the user to search for. You may pass the param multiple times to filter for more than one email
"""

UserFamilyName: TypeAlias = str | Sequence[str]
"""
Family name of the user to search for. You may pass the param multiple times to filter for more than one family name
"""

UserGivenName: TypeAlias = str | Sequence[str]
"""
Given name of the user to search for. You may pass the param multiple times to filter for more than one given name
"""

UserIdParam: TypeAlias = str
"""
User id
"""


class GetUserResponse(TypedDict):
    objects: Sequence[User]
    """
    A list of user objects
    """
