# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: e8d2ba3c791d64bd9c9739303d52e284a43f64c4dec2ad20798b0279f7fa8bab

from typing_extensions import NotRequired
from typing import Any, Literal, TypeAlias, TypedDict
from collections.abc import Mapping, Sequence

from .common import AclObjectType


class DeleteView(TypedDict):
    object_id: str
    """
    The id of the object the view applies to
    """
    object_type: AclObjectType


class ViewDataSearch(TypedDict):
    filter: NotRequired[Sequence[Any] | None]
    match: NotRequired[Sequence[Any] | None]
    sort: NotRequired[Sequence[Any] | None]
    tag: NotRequired[Sequence[Any] | None]


ViewIdParam: TypeAlias = str
"""
View id
"""

ViewName: TypeAlias = str
"""
Name of the view to search for
"""


class Options(TypedDict):
    chartVisibility: NotRequired[Mapping[str, bool] | None]
    frameEnd: NotRequired[str | None]
    frameStart: NotRequired[str | None]
    groupBy: NotRequired[str | None]
    projectId: NotRequired[str | None]
    rangeValue: NotRequired[str | None]
    spanType: NotRequired[Literal["range", "frame"] | None]
    type: NotRequired[Literal["project", "experiment"] | None]
    tzUTC: NotRequired[bool | None]


class ViewOptions1(TypedDict):
    freezeColumns: NotRequired[bool | None]
    options: Options
    viewType: Literal["monitor"]


class ChartAnnotation(TypedDict):
    id: str
    text: str


class ExcludedMeasure(TypedDict):
    type: Literal["none", "score", "metric", "metadata"]
    value: str


class PointSizeMetric(TypedDict):
    type: Literal["none", "score", "metric", "metadata"]
    value: str


class SymbolGrouping(TypedDict):
    type: Literal["none", "score", "metric", "metadata"]
    value: str


TimeRangeFilter = TypedDict(
    "TimeRangeFilter",
    {
        "from": str,
        "to": str,
    },
)


class XAxis(TypedDict):
    type: Literal["none", "score", "metric", "metadata"]
    value: str


class YMetric(TypedDict):
    type: Literal["none", "score", "metric", "metadata"]
    value: str


class ViewOptions2(TypedDict):
    chartAnnotations: NotRequired[Sequence[ChartAnnotation] | None]
    chartHeight: NotRequired[float | None]
    cluster: NotRequired[str | None]
    columnOrder: NotRequired[Sequence[str] | None]
    columnSizing: NotRequired[Mapping[str, float] | None]
    columnVisibility: NotRequired[Mapping[str, bool] | None]
    excludedMeasures: NotRequired[Sequence[ExcludedMeasure] | None]
    freezeColumns: NotRequired[bool | None]
    grouping: NotRequired[str | None]
    layout: NotRequired[str | None]
    pointSizeMetric: NotRequired[PointSizeMetric | None]
    queryShape: NotRequired[Literal["traces", "spans", "topics"] | None]
    rowHeight: NotRequired[str | None]
    symbolGrouping: NotRequired[SymbolGrouping | None]
    tallGroupRows: NotRequired[bool | None]
    timeRangeFilter: NotRequired[str | TimeRangeFilter | None]
    topicMapReportKey: NotRequired[str | None]
    xAxis: NotRequired[XAxis | None]
    xAxisAggregation: NotRequired[str | None]
    """
    One of 'avg', 'sum', 'min', 'max', 'median', 'all'
    """
    yMetric: NotRequired[YMetric | None]


ViewOptions: TypeAlias = ViewOptions1 | ViewOptions2 | None
"""
Options for the view in the app
"""

ViewType: TypeAlias = (
    Literal[
        "projects",
        "experiments",
        "experiment",
        "playgrounds",
        "playground",
        "datasets",
        "dataset",
        "prompts",
        "parameters",
        "tools",
        "scorers",
        "classifiers",
        "logs",
        "monitor",
        "for_review_project_log",
        "for_review_experiments",
        "for_review_datasets",
    ]
    | None
)
"""
Type of object that the view corresponds to.
"""


class ViewData(TypedDict):
    custom_charts: NotRequired[Any | None]
    search: NotRequired[ViewDataSearch | None]


class CreateView(TypedDict):
    deleted_at: NotRequired[str | None]
    """
    Date of role deletion, or null if the role is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the view
    """
    name: str
    """
    Name of the view
    """
    object_id: str
    """
    The id of the object the view applies to
    """
    object_type: AclObjectType
    options: NotRequired[ViewOptions]
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the view
    """
    view_data: NotRequired[ViewData | None]
    view_type: (
        Literal[
            "projects",
            "experiments",
            "experiment",
            "playgrounds",
            "playground",
            "datasets",
            "dataset",
            "prompts",
            "parameters",
            "tools",
            "scorers",
            "classifiers",
            "logs",
            "monitor",
            "for_review_project_log",
            "for_review_experiments",
            "for_review_datasets",
        ]
        | None
    )
    """
    Type of object that the view corresponds to.
    """


class PatchView(TypedDict):
    description: NotRequired[str | None]
    """
    Textual description of the view
    """
    name: NotRequired[str | None]
    """
    Name of the view
    """
    object_id: str
    """
    The id of the object the view applies to
    """
    object_type: AclObjectType
    options: NotRequired[ViewOptions]
    starred: NotRequired[bool]
    """
    Whether the view is starred in its project
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the view
    """
    view_data: NotRequired[ViewData | None]
    view_type: NotRequired[
        Literal[
            "projects",
            "experiments",
            "experiment",
            "playgrounds",
            "playground",
            "datasets",
            "dataset",
            "prompts",
            "parameters",
            "tools",
            "scorers",
            "classifiers",
            "logs",
            "monitor",
            "for_review_project_log",
            "for_review_experiments",
            "for_review_datasets",
        ]
        | None
    ]
    """
    Type of object that the view corresponds to.
    """


class View(TypedDict):
    created: NotRequired[str | None]
    """
    Date of view creation
    """
    deleted_at: NotRequired[str | None]
    """
    Date of role deletion, or null if the role is still active
    """
    description: NotRequired[str | None]
    """
    Textual description of the view
    """
    id: str
    """
    Unique identifier for the view
    """
    name: str
    """
    Name of the view
    """
    object_id: str
    """
    The id of the object the view applies to
    """
    object_type: AclObjectType
    options: NotRequired[ViewOptions]
    starred: NotRequired[bool]
    """
    Whether the view is starred in its project
    """
    updated_at: NotRequired[str | None]
    """
    Date of last view update
    """
    user_id: NotRequired[str | None]
    """
    Identifies the user who created the view
    """
    view_data: NotRequired[ViewData | None]
    view_type: (
        Literal[
            "projects",
            "experiments",
            "experiment",
            "playgrounds",
            "playground",
            "datasets",
            "dataset",
            "prompts",
            "parameters",
            "tools",
            "scorers",
            "classifiers",
            "logs",
            "monitor",
            "for_review_project_log",
            "for_review_experiments",
            "for_review_datasets",
        ]
        | None
    )
    """
    Type of object that the view corresponds to.
    """


class GetViewResponse(TypedDict):
    objects: Sequence[View]
    """
    A list of view objects
    """
