# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 9daf27f19d9e0340304d7a3e7d0edb28380b94c6
# OpenAPI spec SHA-256: 5ec753c0263c0c44cd04f741edfc7e8bad491cc25a2113d029e84edc076520f0
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 730aa723c7c8b52ae9d2647c910a95e3402ed18b65dbb744255877b93c3fd421

"""Private generated REST API implementation.

Import submodules explicitly (``from braintrust.api._generated import models``); importing this
package pulls in no models.
"""
