# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 66eed24b98cd0f5609c9f524230a61497f7fd77d
# OpenAPI spec SHA-256: 877ab1fd2a22c407af1975a2f880170fb5dc2d31f550c1ce611b407037e4f221
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 730aa723c7c8b52ae9d2647c910a95e3402ed18b65dbb744255877b93c3fd421

"""Private generated REST API implementation.

Import submodules explicitly (``from braintrust.api._generated import models``); importing this
package pulls in no models.
"""
