# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 730aa723c7c8b52ae9d2647c910a95e3402ed18b65dbb744255877b93c3fd421

"""Private generated REST API implementation.

Import submodules explicitly (``from braintrust.api._generated import models``); importing this
package pulls in no models.
"""
