# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: f6e047cca4248110070e62fa23535ca244f4a8136afe651d25c9f0ff94f687e1

"""Generated Acls REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.acls import (
    Acl,
    AclBatchUpdateRequest,
    AclBatchUpdateResponse,
    AclIdParam,
    AclItem,
    AclListGroupId,
    AclListOrgObjectId,
    AclListOrgObjectType,
    AclListOrgResponse,
    AclListPermission,
    AclListRestrictObjectType,
    AclListRoleId,
    AclListUserId,
    GetAclResponse,
)
from .models.common import AclObjectId, AclObjectType, AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter


POST_ACL = Operation(
    operation_id="postAcl",
    method="POST",
    path="/v1/acl",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_ACL = Operation(
    operation_id="deleteAcl",
    method="DELETE",
    path="/v1/acl",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_ACL = Operation(
    operation_id="getAcl",
    method="GET",
    path="/v1/acl",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_type",
            name="object_type",
            location="query",
            required=True,
        ),
        Parameter(
            argument_name="object_id",
            name="object_id",
            location="query",
            required=True,
        ),
        Parameter(
            argument_name="user_id",
            name="user_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="group_id",
            name="group_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="permission",
            name="permission",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="restrict_object_type",
            name="restrict_object_type",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="role_id",
            name="role_id",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_ACL_ID = Operation(
    operation_id="getAclId",
    method="GET",
    path="/v1/acl/{acl_id}",
    parameters=(
        Parameter(
            argument_name="acl_id",
            name="acl_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


DELETE_ACL_ID = Operation(
    operation_id="deleteAclId",
    method="DELETE",
    path="/v1/acl/{acl_id}",
    parameters=(
        Parameter(
            argument_name="acl_id",
            name="acl_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


ACL_BATCH_UPDATE = Operation(
    operation_id="aclBatchUpdate",
    method="POST",
    path="/v1/acl/batch_update",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


ACL_LIST_ORG = Operation(
    operation_id="aclListOrg",
    method="GET",
    path="/v1/acl/list_org",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_type",
            name="object_type",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_id",
            name="object_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="user_id",
            name="user_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="group_id",
            name="group_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="permission",
            name="permission",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="restrict_object_type",
            name="restrict_object_type",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="role_id",
            name="role_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


OPERATIONS = {
    "postAcl": POST_ACL,
    "deleteAcl": DELETE_ACL,
    "getAcl": GET_ACL,
    "getAclId": GET_ACL_ID,
    "deleteAclId": DELETE_ACL_ID,
    "aclBatchUpdate": ACL_BATCH_UPDATE,
    "aclListOrg": ACL_LIST_ORG,
}


class AclsAPI(ResourceAPI):
    """Generated Acls REST API."""

    def post_acl(
        self,
        *,
        body: "AclItem",
    ) -> "Acl":
        return cast(
            "Acl",
            self.execute(
                POST_ACL,
                body=body,
            ),
        )

    def delete_acl(
        self,
        *,
        body: "AclItem",
    ) -> "Acl":
        return cast(
            "Acl",
            self.execute(
                DELETE_ACL,
                body=body,
            ),
        )

    def get_acl(
        self,
        object_type: "AclObjectType",
        object_id: "AclObjectId",
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        user_id: "AclListUserId | None" = None,
        group_id: "AclListGroupId | None" = None,
        permission: "AclListPermission | None" = None,
        restrict_object_type: "AclListRestrictObjectType | None" = None,
        role_id: "AclListRoleId | None" = None,
    ) -> "GetAclResponse":
        return cast(
            "GetAclResponse",
            self.execute(
                GET_ACL,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "object_type": object_type,
                    "object_id": object_id,
                    "user_id": user_id,
                    "group_id": group_id,
                    "permission": permission,
                    "restrict_object_type": restrict_object_type,
                    "role_id": role_id,
                },
            ),
        )

    def get_acl_id(
        self,
        acl_id: "AclIdParam",
    ) -> "Acl":
        return cast(
            "Acl",
            self.execute(
                GET_ACL_ID,
                path_parameters={"acl_id": acl_id},
            ),
        )

    def delete_acl_id(
        self,
        acl_id: "AclIdParam",
    ) -> "Acl":
        return cast(
            "Acl",
            self.execute(
                DELETE_ACL_ID,
                path_parameters={"acl_id": acl_id},
            ),
        )

    def acl_batch_update(
        self,
        *,
        body: "AclBatchUpdateRequest | None" = None,
    ) -> "AclBatchUpdateResponse":
        return cast(
            "AclBatchUpdateResponse",
            self.execute(
                ACL_BATCH_UPDATE,
                body=body,
            ),
        )

    def acl_list_org(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        ids: "Ids | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        object_type: "AclListOrgObjectType | None" = None,
        object_id: "AclListOrgObjectId | None" = None,
        user_id: "AclListUserId | None" = None,
        group_id: "AclListGroupId | None" = None,
        permission: "AclListPermission | None" = None,
        restrict_object_type: "AclListRestrictObjectType | None" = None,
        role_id: "AclListRoleId | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "AclListOrgResponse":
        return cast(
            "AclListOrgResponse",
            self.execute(
                ACL_LIST_ORG,
                query_parameters={
                    "limit": limit,
                    "ids": ids,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "object_type": object_type,
                    "object_id": object_id,
                    "user_id": user_id,
                    "group_id": group_id,
                    "permission": permission,
                    "restrict_object_type": restrict_object_type,
                    "role_id": role_id,
                    "org_name": org_name,
                },
            ),
        )
