# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 91870cec12a1ea3a24bf9925387834e703dc75dedd95b1fbe127af6aa3fa5d8a

"""Generated Agents REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.agents import Agent, AgentIdParam, AgentName, CreateAgent, GetAgentResponse, PatchAgent
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter


POST_AGENT = Operation(
    operation_id="postAgent",
    method="POST",
    path="/v1/agent",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_AGENT = Operation(
    operation_id="putAgent",
    method="PUT",
    path="/v1/agent",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_AGENT = Operation(
    operation_id="getAgent",
    method="GET",
    path="/v1/agent",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="agent_name",
            name="agent_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_AGENT_ID = Operation(
    operation_id="getAgentId",
    method="GET",
    path="/v1/agent/{agent_id}",
    parameters=(
        Parameter(
            argument_name="agent_id",
            name="agent_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_AGENT_ID = Operation(
    operation_id="patchAgentId",
    method="PATCH",
    path="/v1/agent/{agent_id}",
    parameters=(
        Parameter(
            argument_name="agent_id",
            name="agent_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_AGENT_ID = Operation(
    operation_id="deleteAgentId",
    method="DELETE",
    path="/v1/agent/{agent_id}",
    parameters=(
        Parameter(
            argument_name="agent_id",
            name="agent_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postAgent": POST_AGENT,
    "putAgent": PUT_AGENT,
    "getAgent": GET_AGENT,
    "getAgentId": GET_AGENT_ID,
    "patchAgentId": PATCH_AGENT_ID,
    "deleteAgentId": DELETE_AGENT_ID,
}


class AgentsAPI(ResourceAPI):
    """Generated Agents REST API."""

    def post_agent(
        self,
        *,
        body: "CreateAgent",
    ) -> "Agent":
        return cast(
            "Agent",
            self.execute(
                POST_AGENT,
                body=body,
            ),
        )

    def put_agent(
        self,
        *,
        body: "CreateAgent",
    ) -> "Agent":
        return cast(
            "Agent",
            self.execute(
                PUT_AGENT,
                body=body,
            ),
        )

    def get_agent(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        agent_name: "AgentName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetAgentResponse":
        return cast(
            "GetAgentResponse",
            self.execute(
                GET_AGENT,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "agent_name": agent_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_agent_id(
        self,
        agent_id: "AgentIdParam",
    ) -> "Agent":
        return cast(
            "Agent",
            self.execute(
                GET_AGENT_ID,
                path_parameters={"agent_id": agent_id},
            ),
        )

    def patch_agent_id(
        self,
        agent_id: "AgentIdParam",
        *,
        body: "PatchAgent | None" = None,
    ) -> "Agent":
        return cast(
            "Agent",
            self.execute(
                PATCH_AGENT_ID,
                path_parameters={"agent_id": agent_id},
                body=body,
            ),
        )

    def delete_agent_id(
        self,
        agent_id: "AgentIdParam",
    ) -> "Agent":
        return cast(
            "Agent",
            self.execute(
                DELETE_AGENT_ID,
                path_parameters={"agent_id": agent_id},
            ),
        )
