# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 23a87735501958acd619fa0721760d0b9e7c495142fe6f40909a219df40d564a

"""Generated AiSecrets REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.ai_secrets import (
    AISecret,
    AISecretType,
    AiSecretIdParam,
    AiSecretName,
    CreateAISecret,
    DeleteAISecret,
    GetAiSecretResponse,
    PatchAISecret,
)
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter


POST_AI_SECRET = Operation(
    operation_id="postAiSecret",
    method="POST",
    path="/v1/ai_secret",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_AI_SECRET = Operation(
    operation_id="putAiSecret",
    method="PUT",
    path="/v1/ai_secret",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_AI_SECRET = Operation(
    operation_id="deleteAiSecret",
    method="DELETE",
    path="/v1/ai_secret",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_AI_SECRET = Operation(
    operation_id="getAiSecret",
    method="GET",
    path="/v1/ai_secret",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ai_secret_name",
            name="ai_secret_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ai_secret_type",
            name="ai_secret_type",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_AI_SECRET_ID = Operation(
    operation_id="getAiSecretId",
    method="GET",
    path="/v1/ai_secret/{ai_secret_id}",
    parameters=(
        Parameter(
            argument_name="ai_secret_id",
            name="ai_secret_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_AI_SECRET_ID = Operation(
    operation_id="patchAiSecretId",
    method="PATCH",
    path="/v1/ai_secret/{ai_secret_id}",
    parameters=(
        Parameter(
            argument_name="ai_secret_id",
            name="ai_secret_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_AI_SECRET_ID = Operation(
    operation_id="deleteAiSecretId",
    method="DELETE",
    path="/v1/ai_secret/{ai_secret_id}",
    parameters=(
        Parameter(
            argument_name="ai_secret_id",
            name="ai_secret_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postAiSecret": POST_AI_SECRET,
    "putAiSecret": PUT_AI_SECRET,
    "deleteAiSecret": DELETE_AI_SECRET,
    "getAiSecret": GET_AI_SECRET,
    "getAiSecretId": GET_AI_SECRET_ID,
    "patchAiSecretId": PATCH_AI_SECRET_ID,
    "deleteAiSecretId": DELETE_AI_SECRET_ID,
}


class AiSecretsAPI(ResourceAPI):
    """Generated AiSecrets REST API."""

    def post_ai_secret(
        self,
        *,
        body: "CreateAISecret",
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                POST_AI_SECRET,
                body=body,
            ),
        )

    def put_ai_secret(
        self,
        *,
        body: "CreateAISecret",
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                PUT_AI_SECRET,
                body=body,
            ),
        )

    def delete_ai_secret(
        self,
        *,
        body: "DeleteAISecret",
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                DELETE_AI_SECRET,
                body=body,
            ),
        )

    def get_ai_secret(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        ai_secret_name: "AiSecretName | None" = None,
        org_name: "OrgName | None" = None,
        ai_secret_type: "AISecretType | None" = None,
    ) -> "GetAiSecretResponse":
        return cast(
            "GetAiSecretResponse",
            self.execute(
                GET_AI_SECRET,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "ai_secret_name": ai_secret_name,
                    "org_name": org_name,
                    "ai_secret_type": ai_secret_type,
                },
            ),
        )

    def get_ai_secret_id(
        self,
        ai_secret_id: "AiSecretIdParam",
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                GET_AI_SECRET_ID,
                path_parameters={"ai_secret_id": ai_secret_id},
            ),
        )

    def patch_ai_secret_id(
        self,
        ai_secret_id: "AiSecretIdParam",
        *,
        body: "PatchAISecret | None" = None,
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                PATCH_AI_SECRET_ID,
                path_parameters={"ai_secret_id": ai_secret_id},
                body=body,
            ),
        )

    def delete_ai_secret_id(
        self,
        ai_secret_id: "AiSecretIdParam",
    ) -> "AISecret":
        return cast(
            "AISecret",
            self.execute(
                DELETE_AI_SECRET_ID,
                path_parameters={"ai_secret_id": ai_secret_id},
            ),
        )
