# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: f5a0286093c954f653d2e7b36cdc1a029cfec9605bcbe99d2e1f86dd9f394470

"""Generated ApiKeys REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.api_keys import ApiKey, ApiKeyIdParam, ApiKeyName, GetApiKeyResponse
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter


GET_API_KEY = Operation(
    operation_id="getApiKey",
    method="GET",
    path="/v1/api_key",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="api_key_name",
            name="api_key_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_API_KEY_ID = Operation(
    operation_id="getApiKeyId",
    method="GET",
    path="/v1/api_key/{api_key_id}",
    parameters=(
        Parameter(
            argument_name="api_key_id",
            name="api_key_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


DELETE_API_KEY_ID = Operation(
    operation_id="deleteApiKeyId",
    method="DELETE",
    path="/v1/api_key/{api_key_id}",
    parameters=(
        Parameter(
            argument_name="api_key_id",
            name="api_key_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "getApiKey": GET_API_KEY,
    "getApiKeyId": GET_API_KEY_ID,
    "deleteApiKeyId": DELETE_API_KEY_ID,
}


class ApiKeysAPI(ResourceAPI):
    """Generated ApiKeys REST API."""

    def get_api_key(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        api_key_name: "ApiKeyName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetApiKeyResponse":
        return cast(
            "GetApiKeyResponse",
            self.execute(
                GET_API_KEY,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "api_key_name": api_key_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_api_key_id(
        self,
        api_key_id: "ApiKeyIdParam",
    ) -> "ApiKey":
        return cast(
            "ApiKey",
            self.execute(
                GET_API_KEY_ID,
                path_parameters={"api_key_id": api_key_id},
            ),
        )

    def delete_api_key_id(
        self,
        api_key_id: "ApiKeyIdParam",
    ) -> "ApiKey":
        return cast(
            "ApiKey",
            self.execute(
                DELETE_API_KEY_ID,
                path_parameters={"api_key_id": api_key_id},
            ),
        )
