# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: e6f206dca4fc4e8716ec42f88ed985b4aeaa3abaf6a161cb7c0753e82582fc8a

"""Generated EnvVars REST operations and resource."""

from collections.abc import Mapping

from typing import Any, cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, Ids
from .models.env_vars import EnvVar, EnvVarIdParam, EnvVarName, EnvVarObjectId, EnvVarObjectType, GetEnvVarResponse


POST_ENV_VAR = Operation(
    operation_id="postEnvVar",
    method="POST",
    path="/v1/env_var",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_ENV_VAR = Operation(
    operation_id="putEnvVar",
    method="PUT",
    path="/v1/env_var",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_ENV_VAR = Operation(
    operation_id="getEnvVar",
    method="GET",
    path="/v1/env_var",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="env_var_name",
            name="env_var_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_type",
            name="object_type",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_id",
            name="object_id",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_ENV_VAR_ID = Operation(
    operation_id="getEnvVarId",
    method="GET",
    path="/v1/env_var/{env_var_id}",
    parameters=(
        Parameter(
            argument_name="env_var_id",
            name="env_var_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_ENV_VAR_ID = Operation(
    operation_id="patchEnvVarId",
    method="PATCH",
    path="/v1/env_var/{env_var_id}",
    parameters=(
        Parameter(
            argument_name="env_var_id",
            name="env_var_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_ENV_VAR_ID = Operation(
    operation_id="deleteEnvVarId",
    method="DELETE",
    path="/v1/env_var/{env_var_id}",
    parameters=(
        Parameter(
            argument_name="env_var_id",
            name="env_var_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postEnvVar": POST_ENV_VAR,
    "putEnvVar": PUT_ENV_VAR,
    "getEnvVar": GET_ENV_VAR,
    "getEnvVarId": GET_ENV_VAR_ID,
    "patchEnvVarId": PATCH_ENV_VAR_ID,
    "deleteEnvVarId": DELETE_ENV_VAR_ID,
}


class EnvVarsAPI(ResourceAPI):
    """Generated EnvVars REST API."""

    def post_env_var(
        self,
        *,
        body: "Mapping[str, Any]",
    ) -> "EnvVar":
        return cast(
            "EnvVar",
            self.execute(
                POST_ENV_VAR,
                body=body,
            ),
        )

    def put_env_var(
        self,
        *,
        body: "Mapping[str, Any]",
    ) -> "EnvVar":
        return cast(
            "EnvVar",
            self.execute(
                PUT_ENV_VAR,
                body=body,
            ),
        )

    def get_env_var(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        ids: "Ids | None" = None,
        env_var_name: "EnvVarName | None" = None,
        object_type: "EnvVarObjectType | None" = None,
        object_id: "EnvVarObjectId | None" = None,
    ) -> "GetEnvVarResponse":
        return cast(
            "GetEnvVarResponse",
            self.execute(
                GET_ENV_VAR,
                query_parameters={
                    "limit": limit,
                    "ids": ids,
                    "env_var_name": env_var_name,
                    "object_type": object_type,
                    "object_id": object_id,
                },
            ),
        )

    def get_env_var_id(
        self,
        env_var_id: "EnvVarIdParam",
    ) -> "EnvVar":
        return cast(
            "EnvVar",
            self.execute(
                GET_ENV_VAR_ID,
                path_parameters={"env_var_id": env_var_id},
            ),
        )

    def patch_env_var_id(
        self,
        env_var_id: "EnvVarIdParam",
        *,
        body: "Mapping[str, Any]",
    ) -> "EnvVar":
        return cast(
            "EnvVar",
            self.execute(
                PATCH_ENV_VAR_ID,
                path_parameters={"env_var_id": env_var_id},
                body=body,
            ),
        )

    def delete_env_var_id(
        self,
        env_var_id: "EnvVarIdParam",
    ) -> "EnvVar":
        return cast(
            "EnvVar",
            self.execute(
                DELETE_ENV_VAR_ID,
                path_parameters={"env_var_id": env_var_id},
            ),
        )
