# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: d73bd03a77ebd1c03ee77908c684087905576b76a1bd1ecf816bbecf83386272

"""Generated Environments REST operations and resource."""

from collections.abc import Sequence

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import OrgName
from .models.environments import CreateEnvironment, Environment, ListEnvironmentsResponse, PatchEnvironment


LIST_ENVIRONMENTS = Operation(
    operation_id="listEnvironments",
    method="GET",
    path="/environment",
    parameters=(
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="name",
            name="name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


CREATE_ENVIRONMENT = Operation(
    operation_id="createEnvironment",
    method="POST",
    path="/environment",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_ENVIRONMENT = Operation(
    operation_id="getEnvironment",
    method="GET",
    path="/environment/{environment_id}",
    parameters=(
        Parameter(
            argument_name="environment_id",
            name="environment_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


UPDATE_ENVIRONMENT = Operation(
    operation_id="updateEnvironment",
    method="PATCH",
    path="/environment/{environment_id}",
    parameters=(
        Parameter(
            argument_name="environment_id",
            name="environment_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_ENVIRONMENT = Operation(
    operation_id="deleteEnvironment",
    method="DELETE",
    path="/environment/{environment_id}",
    parameters=(
        Parameter(
            argument_name="environment_id",
            name="environment_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "listEnvironments": LIST_ENVIRONMENTS,
    "createEnvironment": CREATE_ENVIRONMENT,
    "getEnvironment": GET_ENVIRONMENT,
    "updateEnvironment": UPDATE_ENVIRONMENT,
    "deleteEnvironment": DELETE_ENVIRONMENT,
}


class EnvironmentsAPI(ResourceAPI):
    """Generated Environments REST API."""

    def list_environments(
        self,
        *,
        ids: "str | Sequence[str] | None" = None,
        name: "str | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "ListEnvironmentsResponse":
        return cast(
            "ListEnvironmentsResponse",
            self.execute(
                LIST_ENVIRONMENTS,
                query_parameters={"ids": ids, "name": name, "org_name": org_name},
            ),
        )

    def create_environment(
        self,
        *,
        body: "CreateEnvironment | None" = None,
    ) -> "Environment":
        return cast(
            "Environment",
            self.execute(
                CREATE_ENVIRONMENT,
                body=body,
            ),
        )

    def get_environment(
        self,
        environment_id: "str",
    ) -> "Environment":
        return cast(
            "Environment",
            self.execute(
                GET_ENVIRONMENT,
                path_parameters={"environment_id": environment_id},
            ),
        )

    def update_environment(
        self,
        environment_id: "str",
        *,
        body: "PatchEnvironment | None" = None,
    ) -> "Environment":
        return cast(
            "Environment",
            self.execute(
                UPDATE_ENVIRONMENT,
                path_parameters={"environment_id": environment_id},
                body=body,
            ),
        )

    def delete_environment(
        self,
        environment_id: "str",
    ) -> "Environment":
        return cast(
            "Environment",
            self.execute(
                DELETE_ENVIRONMENT,
                path_parameters={"environment_id": environment_id},
            ),
        )
