# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: c1a850487c10705bba39e61f347b1599f7138baef68035558e5fb06e7598636c

"""Generated Functions REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import (
    AppLimitParam,
    EndingBefore,
    Ids,
    OrgName,
    ProjectIdQuery,
    ProjectName,
    PromptEnvironment,
    PromptVersion,
    Slug,
    StartingAfter,
)
from .models.functions import (
    CreateFunction,
    Function,
    FunctionIdParam,
    FunctionName,
    GetFunctionResponse,
    PatchFunction,
)


POST_FUNCTION = Operation(
    operation_id="postFunction",
    method="POST",
    path="/v1/function",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_FUNCTION = Operation(
    operation_id="putFunction",
    method="PUT",
    path="/v1/function",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_FUNCTION = Operation(
    operation_id="getFunction",
    method="GET",
    path="/v1/function",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="function_name",
            name="function_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_name",
            name="project_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="slug",
            name="slug",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="version",
            name="version",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="environment",
            name="environment",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_FUNCTION_ID = Operation(
    operation_id="getFunctionId",
    method="GET",
    path="/v1/function/{function_id}",
    parameters=(
        Parameter(
            argument_name="function_id",
            name="function_id",
            location="path",
            required=True,
        ),
        Parameter(
            argument_name="version",
            name="version",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="environment",
            name="environment",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_FUNCTION_ID = Operation(
    operation_id="patchFunctionId",
    method="PATCH",
    path="/v1/function/{function_id}",
    parameters=(
        Parameter(
            argument_name="function_id",
            name="function_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_FUNCTION_ID = Operation(
    operation_id="deleteFunctionId",
    method="DELETE",
    path="/v1/function/{function_id}",
    parameters=(
        Parameter(
            argument_name="function_id",
            name="function_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postFunction": POST_FUNCTION,
    "putFunction": PUT_FUNCTION,
    "getFunction": GET_FUNCTION,
    "getFunctionId": GET_FUNCTION_ID,
    "patchFunctionId": PATCH_FUNCTION_ID,
    "deleteFunctionId": DELETE_FUNCTION_ID,
}


class FunctionsAPI(ResourceAPI):
    """Generated Functions REST API."""

    def post_function(
        self,
        *,
        body: "CreateFunction",
    ) -> "Function":
        return cast(
            "Function",
            self.execute(
                POST_FUNCTION,
                body=body,
            ),
        )

    def put_function(
        self,
        *,
        body: "CreateFunction",
    ) -> "Function":
        return cast(
            "Function",
            self.execute(
                PUT_FUNCTION,
                body=body,
            ),
        )

    def get_function(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        function_name: "FunctionName | None" = None,
        project_name: "ProjectName | None" = None,
        project_id: "ProjectIdQuery | None" = None,
        slug: "Slug | None" = None,
        version: "PromptVersion | None" = None,
        environment: "PromptEnvironment | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetFunctionResponse":
        return cast(
            "GetFunctionResponse",
            self.execute(
                GET_FUNCTION,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "function_name": function_name,
                    "project_name": project_name,
                    "project_id": project_id,
                    "slug": slug,
                    "version": version,
                    "environment": environment,
                    "org_name": org_name,
                },
            ),
        )

    def get_function_id(
        self,
        function_id: "FunctionIdParam",
        *,
        version: "PromptVersion | None" = None,
        environment: "PromptEnvironment | None" = None,
    ) -> "Function":
        return cast(
            "Function",
            self.execute(
                GET_FUNCTION_ID,
                path_parameters={"function_id": function_id},
                query_parameters={"version": version, "environment": environment},
            ),
        )

    def patch_function_id(
        self,
        function_id: "FunctionIdParam",
        *,
        body: "PatchFunction | None" = None,
    ) -> "Function":
        return cast(
            "Function",
            self.execute(
                PATCH_FUNCTION_ID,
                path_parameters={"function_id": function_id},
                body=body,
            ),
        )

    def delete_function_id(
        self,
        function_id: "FunctionIdParam",
    ) -> "Function":
        return cast(
            "Function",
            self.execute(
                DELETE_FUNCTION_ID,
                path_parameters={"function_id": function_id},
            ),
        )
