# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: cb45f2d3342d4d19d7be553dfd1f5983b4ac76da3967fb3fb361d65e2cfec373

"""Generated Groups REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.groups import CreateGroup, GetGroupResponse, Group, GroupIdParam, GroupName, PatchGroup


POST_GROUP = Operation(
    operation_id="postGroup",
    method="POST",
    path="/v1/group",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_GROUP = Operation(
    operation_id="putGroup",
    method="PUT",
    path="/v1/group",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_GROUP = Operation(
    operation_id="getGroup",
    method="GET",
    path="/v1/group",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="group_name",
            name="group_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_GROUP_ID = Operation(
    operation_id="getGroupId",
    method="GET",
    path="/v1/group/{group_id}",
    parameters=(
        Parameter(
            argument_name="group_id",
            name="group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_GROUP_ID = Operation(
    operation_id="patchGroupId",
    method="PATCH",
    path="/v1/group/{group_id}",
    parameters=(
        Parameter(
            argument_name="group_id",
            name="group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_GROUP_ID = Operation(
    operation_id="deleteGroupId",
    method="DELETE",
    path="/v1/group/{group_id}",
    parameters=(
        Parameter(
            argument_name="group_id",
            name="group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postGroup": POST_GROUP,
    "putGroup": PUT_GROUP,
    "getGroup": GET_GROUP,
    "getGroupId": GET_GROUP_ID,
    "patchGroupId": PATCH_GROUP_ID,
    "deleteGroupId": DELETE_GROUP_ID,
}


class GroupsAPI(ResourceAPI):
    """Generated Groups REST API."""

    def post_group(
        self,
        *,
        body: "CreateGroup",
    ) -> "Group":
        return cast(
            "Group",
            self.execute(
                POST_GROUP,
                body=body,
            ),
        )

    def put_group(
        self,
        *,
        body: "CreateGroup",
    ) -> "Group":
        return cast(
            "Group",
            self.execute(
                PUT_GROUP,
                body=body,
            ),
        )

    def get_group(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        group_name: "GroupName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetGroupResponse":
        return cast(
            "GetGroupResponse",
            self.execute(
                GET_GROUP,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "group_name": group_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_group_id(
        self,
        group_id: "GroupIdParam",
    ) -> "Group":
        return cast(
            "Group",
            self.execute(
                GET_GROUP_ID,
                path_parameters={"group_id": group_id},
            ),
        )

    def patch_group_id(
        self,
        group_id: "GroupIdParam",
        *,
        body: "PatchGroup | None" = None,
    ) -> "Group":
        return cast(
            "Group",
            self.execute(
                PATCH_GROUP_ID,
                path_parameters={"group_id": group_id},
                body=body,
            ),
        )

    def delete_group_id(
        self,
        group_id: "GroupIdParam",
    ) -> "Group":
        return cast(
            "Group",
            self.execute(
                DELETE_GROUP_ID,
                path_parameters={"group_id": group_id},
            ),
        )
