# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 0afa41da9e0b2ef95b538eb2812d9ae48d805484820b215f7241c4ac4ef33ea7

"""Generated McpServers REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.mcp_servers import (
    CreateMCPServer,
    GetMcpServerResponse,
    MCPServer,
    McpServerIdParam,
    McpServerName,
    PatchMCPServer,
)


POST_MCP_SERVER = Operation(
    operation_id="postMcpServer",
    method="POST",
    path="/v1/mcp_server",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_MCP_SERVER = Operation(
    operation_id="putMcpServer",
    method="PUT",
    path="/v1/mcp_server",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_MCP_SERVER = Operation(
    operation_id="getMcpServer",
    method="GET",
    path="/v1/mcp_server",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="mcp_server_name",
            name="mcp_server_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_MCP_SERVER_ID = Operation(
    operation_id="getMcpServerId",
    method="GET",
    path="/v1/mcp_server/{mcp_server_id}",
    parameters=(
        Parameter(
            argument_name="mcp_server_id",
            name="mcp_server_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_MCP_SERVER_ID = Operation(
    operation_id="patchMcpServerId",
    method="PATCH",
    path="/v1/mcp_server/{mcp_server_id}",
    parameters=(
        Parameter(
            argument_name="mcp_server_id",
            name="mcp_server_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_MCP_SERVER_ID = Operation(
    operation_id="deleteMcpServerId",
    method="DELETE",
    path="/v1/mcp_server/{mcp_server_id}",
    parameters=(
        Parameter(
            argument_name="mcp_server_id",
            name="mcp_server_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postMcpServer": POST_MCP_SERVER,
    "putMcpServer": PUT_MCP_SERVER,
    "getMcpServer": GET_MCP_SERVER,
    "getMcpServerId": GET_MCP_SERVER_ID,
    "patchMcpServerId": PATCH_MCP_SERVER_ID,
    "deleteMcpServerId": DELETE_MCP_SERVER_ID,
}


class McpServersAPI(ResourceAPI):
    """Generated McpServers REST API."""

    def post_mcp_server(
        self,
        *,
        body: "CreateMCPServer",
    ) -> "MCPServer":
        return cast(
            "MCPServer",
            self.execute(
                POST_MCP_SERVER,
                body=body,
            ),
        )

    def put_mcp_server(
        self,
        *,
        body: "CreateMCPServer",
    ) -> "MCPServer":
        return cast(
            "MCPServer",
            self.execute(
                PUT_MCP_SERVER,
                body=body,
            ),
        )

    def get_mcp_server(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        mcp_server_name: "McpServerName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetMcpServerResponse":
        return cast(
            "GetMcpServerResponse",
            self.execute(
                GET_MCP_SERVER,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "mcp_server_name": mcp_server_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_mcp_server_id(
        self,
        mcp_server_id: "McpServerIdParam",
    ) -> "MCPServer":
        return cast(
            "MCPServer",
            self.execute(
                GET_MCP_SERVER_ID,
                path_parameters={"mcp_server_id": mcp_server_id},
            ),
        )

    def patch_mcp_server_id(
        self,
        mcp_server_id: "McpServerIdParam",
        *,
        body: "PatchMCPServer | None" = None,
    ) -> "MCPServer":
        return cast(
            "MCPServer",
            self.execute(
                PATCH_MCP_SERVER_ID,
                path_parameters={"mcp_server_id": mcp_server_id},
                body=body,
            ),
        )

    def delete_mcp_server_id(
        self,
        mcp_server_id: "McpServerIdParam",
    ) -> "MCPServer":
        return cast(
            "MCPServer",
            self.execute(
                DELETE_MCP_SERVER_ID,
                path_parameters={"mcp_server_id": mcp_server_id},
            ),
        )
