# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 7c38b2fe1729ef5e1a3f54934cd8d021ffa9de488a5993adfc47bea072caf865

"""Generated OrgAutomations REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.org_automations import (
    CreateOrgAutomation,
    GetOrgAutomationResponse,
    OrgAutomation,
    OrgAutomationIdParam,
    OrgAutomationName,
    PatchOrgAutomation,
)


POST_ORG_AUTOMATION = Operation(
    operation_id="postOrgAutomation",
    method="POST",
    path="/v1/org_automation",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_ORG_AUTOMATION = Operation(
    operation_id="putOrgAutomation",
    method="PUT",
    path="/v1/org_automation",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_ORG_AUTOMATION = Operation(
    operation_id="getOrgAutomation",
    method="GET",
    path="/v1/org_automation",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_automation_name",
            name="org_automation_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_ORG_AUTOMATION_ID = Operation(
    operation_id="getOrgAutomationId",
    method="GET",
    path="/v1/org_automation/{org_automation_id}",
    parameters=(
        Parameter(
            argument_name="org_automation_id",
            name="org_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_ORG_AUTOMATION_ID = Operation(
    operation_id="patchOrgAutomationId",
    method="PATCH",
    path="/v1/org_automation/{org_automation_id}",
    parameters=(
        Parameter(
            argument_name="org_automation_id",
            name="org_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_ORG_AUTOMATION_ID = Operation(
    operation_id="deleteOrgAutomationId",
    method="DELETE",
    path="/v1/org_automation/{org_automation_id}",
    parameters=(
        Parameter(
            argument_name="org_automation_id",
            name="org_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postOrgAutomation": POST_ORG_AUTOMATION,
    "putOrgAutomation": PUT_ORG_AUTOMATION,
    "getOrgAutomation": GET_ORG_AUTOMATION,
    "getOrgAutomationId": GET_ORG_AUTOMATION_ID,
    "patchOrgAutomationId": PATCH_ORG_AUTOMATION_ID,
    "deleteOrgAutomationId": DELETE_ORG_AUTOMATION_ID,
}


class OrgAutomationsAPI(ResourceAPI):
    """Generated OrgAutomations REST API."""

    def post_org_automation(
        self,
        *,
        body: "CreateOrgAutomation",
    ) -> "OrgAutomation":
        return cast(
            "OrgAutomation",
            self.execute(
                POST_ORG_AUTOMATION,
                body=body,
            ),
        )

    def put_org_automation(
        self,
        *,
        body: "CreateOrgAutomation",
    ) -> "OrgAutomation":
        return cast(
            "OrgAutomation",
            self.execute(
                PUT_ORG_AUTOMATION,
                body=body,
            ),
        )

    def get_org_automation(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        org_automation_name: "OrgAutomationName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetOrgAutomationResponse":
        return cast(
            "GetOrgAutomationResponse",
            self.execute(
                GET_ORG_AUTOMATION,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "org_automation_name": org_automation_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_org_automation_id(
        self,
        org_automation_id: "OrgAutomationIdParam",
    ) -> "OrgAutomation":
        return cast(
            "OrgAutomation",
            self.execute(
                GET_ORG_AUTOMATION_ID,
                path_parameters={"org_automation_id": org_automation_id},
            ),
        )

    def patch_org_automation_id(
        self,
        org_automation_id: "OrgAutomationIdParam",
        *,
        body: "PatchOrgAutomation | None" = None,
    ) -> "OrgAutomation":
        return cast(
            "OrgAutomation",
            self.execute(
                PATCH_ORG_AUTOMATION_ID,
                path_parameters={"org_automation_id": org_automation_id},
                body=body,
            ),
        )

    def delete_org_automation_id(
        self,
        org_automation_id: "OrgAutomationIdParam",
    ) -> "OrgAutomation":
        return cast(
            "OrgAutomation",
            self.execute(
                DELETE_ORG_AUTOMATION_ID,
                path_parameters={"org_automation_id": org_automation_id},
            ),
        )
