# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 584a9ceaf40b36bdc383bac62d0942c96ccc17323e702ebb931b188234eef88e

"""Generated Organizations REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.organizations import (
    GetOrganizationResponse,
    Organization,
    OrganizationIdParam,
    PatchOrganization,
    PatchOrganizationMembers,
    PatchOrganizationMembersOutput,
)


GET_ORGANIZATION = Operation(
    operation_id="getOrganization",
    method="GET",
    path="/v1/organization",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_ORGANIZATION_ID = Operation(
    operation_id="getOrganizationId",
    method="GET",
    path="/v1/organization/{organization_id}",
    parameters=(
        Parameter(
            argument_name="organization_id",
            name="organization_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_ORGANIZATION_ID = Operation(
    operation_id="patchOrganizationId",
    method="PATCH",
    path="/v1/organization/{organization_id}",
    parameters=(
        Parameter(
            argument_name="organization_id",
            name="organization_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PATCH_ORGANIZATION_MEMBERS = Operation(
    operation_id="patchOrganizationMembers",
    method="PATCH",
    path="/v1/organization/members",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "getOrganization": GET_ORGANIZATION,
    "getOrganizationId": GET_ORGANIZATION_ID,
    "patchOrganizationId": PATCH_ORGANIZATION_ID,
    "patchOrganizationMembers": PATCH_ORGANIZATION_MEMBERS,
}


class OrganizationsAPI(ResourceAPI):
    """Generated Organizations REST API."""

    def get_organization(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetOrganizationResponse":
        return cast(
            "GetOrganizationResponse",
            self.execute(
                GET_ORGANIZATION,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "org_name": org_name,
                },
            ),
        )

    def get_organization_id(
        self,
        organization_id: "OrganizationIdParam",
    ) -> "Organization":
        return cast(
            "Organization",
            self.execute(
                GET_ORGANIZATION_ID,
                path_parameters={"organization_id": organization_id},
            ),
        )

    def patch_organization_id(
        self,
        organization_id: "OrganizationIdParam",
        *,
        body: "PatchOrganization | None" = None,
    ) -> "Organization":
        return cast(
            "Organization",
            self.execute(
                PATCH_ORGANIZATION_ID,
                path_parameters={"organization_id": organization_id},
                body=body,
            ),
        )

    def patch_organization_members(
        self,
        *,
        body: "PatchOrganizationMembers | None" = None,
    ) -> "PatchOrganizationMembersOutput":
        return cast(
            "PatchOrganizationMembersOutput",
            self.execute(
                PATCH_ORGANIZATION_MEMBERS,
                body=body,
            ),
        )
