# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 708923d503995b70db9549b1b15da470732ef8b7396944bb8b36db23b54869be

"""Generated ProjectGroups REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.project_groups import (
    CreateProjectGroup,
    GetProjectGroupResponse,
    PatchProjectGroup,
    ProjectGroup,
    ProjectGroupIdParam,
    ProjectGroupName,
)


POST_PROJECT_GROUP = Operation(
    operation_id="postProjectGroup",
    method="POST",
    path="/v1/project_group",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_PROJECT_GROUP = Operation(
    operation_id="putProjectGroup",
    method="PUT",
    path="/v1/project_group",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_PROJECT_GROUP = Operation(
    operation_id="getProjectGroup",
    method="GET",
    path="/v1/project_group",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_group_name",
            name="project_group_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROJECT_GROUP_ID = Operation(
    operation_id="getProjectGroupId",
    method="GET",
    path="/v1/project_group/{project_group_id}",
    parameters=(
        Parameter(
            argument_name="project_group_id",
            name="project_group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROJECT_GROUP_ID = Operation(
    operation_id="patchProjectGroupId",
    method="PATCH",
    path="/v1/project_group/{project_group_id}",
    parameters=(
        Parameter(
            argument_name="project_group_id",
            name="project_group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROJECT_GROUP_ID = Operation(
    operation_id="deleteProjectGroupId",
    method="DELETE",
    path="/v1/project_group/{project_group_id}",
    parameters=(
        Parameter(
            argument_name="project_group_id",
            name="project_group_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postProjectGroup": POST_PROJECT_GROUP,
    "putProjectGroup": PUT_PROJECT_GROUP,
    "getProjectGroup": GET_PROJECT_GROUP,
    "getProjectGroupId": GET_PROJECT_GROUP_ID,
    "patchProjectGroupId": PATCH_PROJECT_GROUP_ID,
    "deleteProjectGroupId": DELETE_PROJECT_GROUP_ID,
}


class ProjectGroupsAPI(ResourceAPI):
    """Generated ProjectGroups REST API."""

    def post_project_group(
        self,
        *,
        body: "CreateProjectGroup",
    ) -> "ProjectGroup":
        return cast(
            "ProjectGroup",
            self.execute(
                POST_PROJECT_GROUP,
                body=body,
            ),
        )

    def put_project_group(
        self,
        *,
        body: "CreateProjectGroup",
    ) -> "ProjectGroup":
        return cast(
            "ProjectGroup",
            self.execute(
                PUT_PROJECT_GROUP,
                body=body,
            ),
        )

    def get_project_group(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        project_group_name: "ProjectGroupName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetProjectGroupResponse":
        return cast(
            "GetProjectGroupResponse",
            self.execute(
                GET_PROJECT_GROUP,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "project_group_name": project_group_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_project_group_id(
        self,
        project_group_id: "ProjectGroupIdParam",
    ) -> "ProjectGroup":
        return cast(
            "ProjectGroup",
            self.execute(
                GET_PROJECT_GROUP_ID,
                path_parameters={"project_group_id": project_group_id},
            ),
        )

    def patch_project_group_id(
        self,
        project_group_id: "ProjectGroupIdParam",
        *,
        body: "PatchProjectGroup | None" = None,
    ) -> "ProjectGroup":
        return cast(
            "ProjectGroup",
            self.execute(
                PATCH_PROJECT_GROUP_ID,
                path_parameters={"project_group_id": project_group_id},
                body=body,
            ),
        )

    def delete_project_group_id(
        self,
        project_group_id: "ProjectGroupIdParam",
    ) -> "ProjectGroup":
        return cast(
            "ProjectGroup",
            self.execute(
                DELETE_PROJECT_GROUP_ID,
                path_parameters={"project_group_id": project_group_id},
            ),
        )
