# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: b8c7db2fcb18903fe2e4e665e5c08e6341e492e7285f179c785c93f53c099a19

"""Generated ProjectScores REST operations and resource."""

from collections.abc import Sequence

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, ProjectIdQuery, ProjectName, StartingAfter
from .models.project_scores import (
    CreateProjectScore,
    GetProjectScoreResponse,
    PatchProjectScore,
    ProjectScore,
    ProjectScoreIdParam,
    ProjectScoreName,
    ProjectScoreType,
)


POST_PROJECT_SCORE = Operation(
    operation_id="postProjectScore",
    method="POST",
    path="/v1/project_score",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_PROJECT_SCORE = Operation(
    operation_id="putProjectScore",
    method="PUT",
    path="/v1/project_score",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_PROJECT_SCORE = Operation(
    operation_id="getProjectScore",
    method="GET",
    path="/v1/project_score",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_score_name",
            name="project_score_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_name",
            name="project_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="score_type",
            name="score_type",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROJECT_SCORE_ID = Operation(
    operation_id="getProjectScoreId",
    method="GET",
    path="/v1/project_score/{project_score_id}",
    parameters=(
        Parameter(
            argument_name="project_score_id",
            name="project_score_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROJECT_SCORE_ID = Operation(
    operation_id="patchProjectScoreId",
    method="PATCH",
    path="/v1/project_score/{project_score_id}",
    parameters=(
        Parameter(
            argument_name="project_score_id",
            name="project_score_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROJECT_SCORE_ID = Operation(
    operation_id="deleteProjectScoreId",
    method="DELETE",
    path="/v1/project_score/{project_score_id}",
    parameters=(
        Parameter(
            argument_name="project_score_id",
            name="project_score_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postProjectScore": POST_PROJECT_SCORE,
    "putProjectScore": PUT_PROJECT_SCORE,
    "getProjectScore": GET_PROJECT_SCORE,
    "getProjectScoreId": GET_PROJECT_SCORE_ID,
    "patchProjectScoreId": PATCH_PROJECT_SCORE_ID,
    "deleteProjectScoreId": DELETE_PROJECT_SCORE_ID,
}


class ProjectScoresAPI(ResourceAPI):
    """Generated ProjectScores REST API."""

    def post_project_score(
        self,
        *,
        body: "CreateProjectScore",
    ) -> "ProjectScore":
        return cast(
            "ProjectScore",
            self.execute(
                POST_PROJECT_SCORE,
                body=body,
            ),
        )

    def put_project_score(
        self,
        *,
        body: "CreateProjectScore",
    ) -> "ProjectScore":
        return cast(
            "ProjectScore",
            self.execute(
                PUT_PROJECT_SCORE,
                body=body,
            ),
        )

    def get_project_score(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        project_score_name: "ProjectScoreName | None" = None,
        project_name: "ProjectName | None" = None,
        project_id: "ProjectIdQuery | None" = None,
        org_name: "OrgName | None" = None,
        score_type: "ProjectScoreType | Sequence[ProjectScoreType] | None" = None,
    ) -> "GetProjectScoreResponse":
        return cast(
            "GetProjectScoreResponse",
            self.execute(
                GET_PROJECT_SCORE,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "project_score_name": project_score_name,
                    "project_name": project_name,
                    "project_id": project_id,
                    "org_name": org_name,
                    "score_type": score_type,
                },
            ),
        )

    def get_project_score_id(
        self,
        project_score_id: "ProjectScoreIdParam",
    ) -> "ProjectScore":
        return cast(
            "ProjectScore",
            self.execute(
                GET_PROJECT_SCORE_ID,
                path_parameters={"project_score_id": project_score_id},
            ),
        )

    def patch_project_score_id(
        self,
        project_score_id: "ProjectScoreIdParam",
        *,
        body: "PatchProjectScore | None" = None,
    ) -> "ProjectScore":
        return cast(
            "ProjectScore",
            self.execute(
                PATCH_PROJECT_SCORE_ID,
                path_parameters={"project_score_id": project_score_id},
                body=body,
            ),
        )

    def delete_project_score_id(
        self,
        project_score_id: "ProjectScoreIdParam",
    ) -> "ProjectScore":
        return cast(
            "ProjectScore",
            self.execute(
                DELETE_PROJECT_SCORE_ID,
                path_parameters={"project_score_id": project_score_id},
            ),
        )
