# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 2c3e34042b60d251ff81dfe467a1f2958d7baadf9e8888bac93c6c452b941b99

"""Generated ProjectAutomations REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.project_automations import (
    CreateProjectAutomation,
    GetProjectAutomationResponse,
    PatchProjectAutomation,
    ProjectAutomation,
    ProjectAutomationIdParam,
    ProjectAutomationName,
)


POST_PROJECT_AUTOMATION = Operation(
    operation_id="postProjectAutomation",
    method="POST",
    path="/v1/project_automation",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_PROJECT_AUTOMATION = Operation(
    operation_id="putProjectAutomation",
    method="PUT",
    path="/v1/project_automation",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_PROJECT_AUTOMATION = Operation(
    operation_id="getProjectAutomation",
    method="GET",
    path="/v1/project_automation",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_automation_name",
            name="project_automation_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROJECT_AUTOMATION_ID = Operation(
    operation_id="getProjectAutomationId",
    method="GET",
    path="/v1/project_automation/{project_automation_id}",
    parameters=(
        Parameter(
            argument_name="project_automation_id",
            name="project_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROJECT_AUTOMATION_ID = Operation(
    operation_id="patchProjectAutomationId",
    method="PATCH",
    path="/v1/project_automation/{project_automation_id}",
    parameters=(
        Parameter(
            argument_name="project_automation_id",
            name="project_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROJECT_AUTOMATION_ID = Operation(
    operation_id="deleteProjectAutomationId",
    method="DELETE",
    path="/v1/project_automation/{project_automation_id}",
    parameters=(
        Parameter(
            argument_name="project_automation_id",
            name="project_automation_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postProjectAutomation": POST_PROJECT_AUTOMATION,
    "putProjectAutomation": PUT_PROJECT_AUTOMATION,
    "getProjectAutomation": GET_PROJECT_AUTOMATION,
    "getProjectAutomationId": GET_PROJECT_AUTOMATION_ID,
    "patchProjectAutomationId": PATCH_PROJECT_AUTOMATION_ID,
    "deleteProjectAutomationId": DELETE_PROJECT_AUTOMATION_ID,
}


class ProjectAutomationsAPI(ResourceAPI):
    """Generated ProjectAutomations REST API."""

    def post_project_automation(
        self,
        *,
        body: "CreateProjectAutomation",
    ) -> "ProjectAutomation":
        return cast(
            "ProjectAutomation",
            self.execute(
                POST_PROJECT_AUTOMATION,
                body=body,
            ),
        )

    def put_project_automation(
        self,
        *,
        body: "CreateProjectAutomation",
    ) -> "ProjectAutomation":
        return cast(
            "ProjectAutomation",
            self.execute(
                PUT_PROJECT_AUTOMATION,
                body=body,
            ),
        )

    def get_project_automation(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        project_automation_name: "ProjectAutomationName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetProjectAutomationResponse":
        return cast(
            "GetProjectAutomationResponse",
            self.execute(
                GET_PROJECT_AUTOMATION,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "project_automation_name": project_automation_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_project_automation_id(
        self,
        project_automation_id: "ProjectAutomationIdParam",
    ) -> "ProjectAutomation":
        return cast(
            "ProjectAutomation",
            self.execute(
                GET_PROJECT_AUTOMATION_ID,
                path_parameters={"project_automation_id": project_automation_id},
            ),
        )

    def patch_project_automation_id(
        self,
        project_automation_id: "ProjectAutomationIdParam",
        *,
        body: "PatchProjectAutomation | None" = None,
    ) -> "ProjectAutomation":
        return cast(
            "ProjectAutomation",
            self.execute(
                PATCH_PROJECT_AUTOMATION_ID,
                path_parameters={"project_automation_id": project_automation_id},
                body=body,
            ),
        )

    def delete_project_automation_id(
        self,
        project_automation_id: "ProjectAutomationIdParam",
    ) -> "ProjectAutomation":
        return cast(
            "ProjectAutomation",
            self.execute(
                DELETE_PROJECT_AUTOMATION_ID,
                path_parameters={"project_automation_id": project_automation_id},
            ),
        )
