# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: da2fc73d69463add8ff2c479671812972b30b4705c38c1edec9c9bf270077c19

"""Generated ProjectTags REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, ProjectIdQuery, ProjectName, StartingAfter
from .models.project_tags import (
    CreateProjectTag,
    GetProjectTagResponse,
    PatchProjectTag,
    ProjectTag,
    ProjectTagIdParam,
    ProjectTagName,
)


POST_PROJECT_TAG = Operation(
    operation_id="postProjectTag",
    method="POST",
    path="/v1/project_tag",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_PROJECT_TAG = Operation(
    operation_id="putProjectTag",
    method="PUT",
    path="/v1/project_tag",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_PROJECT_TAG = Operation(
    operation_id="getProjectTag",
    method="GET",
    path="/v1/project_tag",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_tag_name",
            name="project_tag_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_name",
            name="project_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROJECT_TAG_ID = Operation(
    operation_id="getProjectTagId",
    method="GET",
    path="/v1/project_tag/{project_tag_id}",
    parameters=(
        Parameter(
            argument_name="project_tag_id",
            name="project_tag_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROJECT_TAG_ID = Operation(
    operation_id="patchProjectTagId",
    method="PATCH",
    path="/v1/project_tag/{project_tag_id}",
    parameters=(
        Parameter(
            argument_name="project_tag_id",
            name="project_tag_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROJECT_TAG_ID = Operation(
    operation_id="deleteProjectTagId",
    method="DELETE",
    path="/v1/project_tag/{project_tag_id}",
    parameters=(
        Parameter(
            argument_name="project_tag_id",
            name="project_tag_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postProjectTag": POST_PROJECT_TAG,
    "putProjectTag": PUT_PROJECT_TAG,
    "getProjectTag": GET_PROJECT_TAG,
    "getProjectTagId": GET_PROJECT_TAG_ID,
    "patchProjectTagId": PATCH_PROJECT_TAG_ID,
    "deleteProjectTagId": DELETE_PROJECT_TAG_ID,
}


class ProjectTagsAPI(ResourceAPI):
    """Generated ProjectTags REST API."""

    def post_project_tag(
        self,
        *,
        body: "CreateProjectTag",
    ) -> "ProjectTag":
        return cast(
            "ProjectTag",
            self.execute(
                POST_PROJECT_TAG,
                body=body,
            ),
        )

    def put_project_tag(
        self,
        *,
        body: "CreateProjectTag",
    ) -> "ProjectTag":
        return cast(
            "ProjectTag",
            self.execute(
                PUT_PROJECT_TAG,
                body=body,
            ),
        )

    def get_project_tag(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        project_tag_name: "ProjectTagName | None" = None,
        project_name: "ProjectName | None" = None,
        project_id: "ProjectIdQuery | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetProjectTagResponse":
        return cast(
            "GetProjectTagResponse",
            self.execute(
                GET_PROJECT_TAG,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "project_tag_name": project_tag_name,
                    "project_name": project_name,
                    "project_id": project_id,
                    "org_name": org_name,
                },
            ),
        )

    def get_project_tag_id(
        self,
        project_tag_id: "ProjectTagIdParam",
    ) -> "ProjectTag":
        return cast(
            "ProjectTag",
            self.execute(
                GET_PROJECT_TAG_ID,
                path_parameters={"project_tag_id": project_tag_id},
            ),
        )

    def patch_project_tag_id(
        self,
        project_tag_id: "ProjectTagIdParam",
        *,
        body: "PatchProjectTag | None" = None,
    ) -> "ProjectTag":
        return cast(
            "ProjectTag",
            self.execute(
                PATCH_PROJECT_TAG_ID,
                path_parameters={"project_tag_id": project_tag_id},
                body=body,
            ),
        )

    def delete_project_tag_id(
        self,
        project_tag_id: "ProjectTagIdParam",
    ) -> "ProjectTag":
        return cast(
            "ProjectTag",
            self.execute(
                DELETE_PROJECT_TAG_ID,
                path_parameters={"project_tag_id": project_tag_id},
            ),
        )
