# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: af02a43ff12855234f1d45dc636fa0b66579dfb9e823a1aab9c08905407bd12c

"""Generated Projects REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, ProjectName, StartingAfter
from .models.projects import CreateProject, GetProjectResponse, PatchProject, Project, ProjectIdParam


POST_PROJECT = Operation(
    operation_id="postProject",
    method="POST",
    path="/v1/project",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.IDEMPOTENT_WRITE,
)


GET_PROJECT = Operation(
    operation_id="getProject",
    method="GET",
    path="/v1/project",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_name",
            name="project_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROJECT_ID = Operation(
    operation_id="getProjectId",
    method="GET",
    path="/v1/project/{project_id}",
    parameters=(
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROJECT_ID = Operation(
    operation_id="patchProjectId",
    method="PATCH",
    path="/v1/project/{project_id}",
    parameters=(
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROJECT_ID = Operation(
    operation_id="deleteProjectId",
    method="DELETE",
    path="/v1/project/{project_id}",
    parameters=(
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postProject": POST_PROJECT,
    "getProject": GET_PROJECT,
    "getProjectId": GET_PROJECT_ID,
    "patchProjectId": PATCH_PROJECT_ID,
    "deleteProjectId": DELETE_PROJECT_ID,
}


class ProjectsAPI(ResourceAPI):
    """Generated Projects REST API."""

    def post_project(
        self,
        *,
        body: "CreateProject",
    ) -> "Project":
        return cast(
            "Project",
            self.execute(
                POST_PROJECT,
                body=body,
            ),
        )

    def get_project(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        project_name: "ProjectName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetProjectResponse":
        return cast(
            "GetProjectResponse",
            self.execute(
                GET_PROJECT,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "project_name": project_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_project_id(
        self,
        project_id: "ProjectIdParam",
    ) -> "Project":
        return cast(
            "Project",
            self.execute(
                GET_PROJECT_ID,
                path_parameters={"project_id": project_id},
            ),
        )

    def patch_project_id(
        self,
        project_id: "ProjectIdParam",
        *,
        body: "PatchProject | None" = None,
    ) -> "Project":
        return cast(
            "Project",
            self.execute(
                PATCH_PROJECT_ID,
                path_parameters={"project_id": project_id},
                body=body,
            ),
        )

    def delete_project_id(
        self,
        project_id: "ProjectIdParam",
    ) -> "Project":
        return cast(
            "Project",
            self.execute(
                DELETE_PROJECT_ID,
                path_parameters={"project_id": project_id},
            ),
        )
