# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 2f8d43a3bacf5e304ec52fca1dd92b7c050bbdda4033df72c96c39d2a584380b

"""Generated Prompts REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, ProjectIdQuery, ProjectName, StartingAfter
from .models.prompts import (
    CreatePrompt,
    GetPromptResponse,
    PatchPrompt,
    Prompt,
    PromptEnvironment,
    PromptIdParam,
    PromptName,
    PromptVersion,
    Slug,
)


POST_PROMPT = Operation(
    operation_id="postPrompt",
    method="POST",
    path="/v1/prompt",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_PROMPT = Operation(
    operation_id="putPrompt",
    method="PUT",
    path="/v1/prompt",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_PROMPT = Operation(
    operation_id="getPrompt",
    method="GET",
    path="/v1/prompt",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="prompt_name",
            name="prompt_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_name",
            name="project_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="project_id",
            name="project_id",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="slug",
            name="slug",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="version",
            name="version",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="environment",
            name="environment",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_PROMPT_ID = Operation(
    operation_id="getPromptId",
    method="GET",
    path="/v1/prompt/{prompt_id}",
    parameters=(
        Parameter(
            argument_name="prompt_id",
            name="prompt_id",
            location="path",
            required=True,
        ),
        Parameter(
            argument_name="version",
            name="version",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="environment",
            name="environment",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_PROMPT_ID = Operation(
    operation_id="patchPromptId",
    method="PATCH",
    path="/v1/prompt/{prompt_id}",
    parameters=(
        Parameter(
            argument_name="prompt_id",
            name="prompt_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_PROMPT_ID = Operation(
    operation_id="deletePromptId",
    method="DELETE",
    path="/v1/prompt/{prompt_id}",
    parameters=(
        Parameter(
            argument_name="prompt_id",
            name="prompt_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postPrompt": POST_PROMPT,
    "putPrompt": PUT_PROMPT,
    "getPrompt": GET_PROMPT,
    "getPromptId": GET_PROMPT_ID,
    "patchPromptId": PATCH_PROMPT_ID,
    "deletePromptId": DELETE_PROMPT_ID,
}


class PromptsAPI(ResourceAPI):
    """Generated Prompts REST API."""

    def post_prompt(
        self,
        *,
        body: "CreatePrompt",
    ) -> "Prompt":
        return cast(
            "Prompt",
            self.execute(
                POST_PROMPT,
                body=body,
            ),
        )

    def put_prompt(
        self,
        *,
        body: "CreatePrompt",
    ) -> "Prompt":
        return cast(
            "Prompt",
            self.execute(
                PUT_PROMPT,
                body=body,
            ),
        )

    def get_prompt(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        prompt_name: "PromptName | None" = None,
        project_name: "ProjectName | None" = None,
        project_id: "ProjectIdQuery | None" = None,
        slug: "Slug | None" = None,
        version: "PromptVersion | None" = None,
        environment: "PromptEnvironment | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetPromptResponse":
        return cast(
            "GetPromptResponse",
            self.execute(
                GET_PROMPT,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "prompt_name": prompt_name,
                    "project_name": project_name,
                    "project_id": project_id,
                    "slug": slug,
                    "version": version,
                    "environment": environment,
                    "org_name": org_name,
                },
            ),
        )

    def get_prompt_id(
        self,
        prompt_id: "PromptIdParam",
        *,
        version: "PromptVersion | None" = None,
        environment: "PromptEnvironment | None" = None,
    ) -> "Prompt":
        return cast(
            "Prompt",
            self.execute(
                GET_PROMPT_ID,
                path_parameters={"prompt_id": prompt_id},
                query_parameters={"version": version, "environment": environment},
            ),
        )

    def patch_prompt_id(
        self,
        prompt_id: "PromptIdParam",
        *,
        body: "PatchPrompt | None" = None,
    ) -> "Prompt":
        return cast(
            "Prompt",
            self.execute(
                PATCH_PROMPT_ID,
                path_parameters={"prompt_id": prompt_id},
                body=body,
            ),
        )

    def delete_prompt_id(
        self,
        prompt_id: "PromptIdParam",
    ) -> "Prompt":
        return cast(
            "Prompt",
            self.execute(
                DELETE_PROMPT_ID,
                path_parameters={"prompt_id": prompt_id},
            ),
        )
