# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: c4bcfe22eb6413d0d926b0f3ddb501e0e1df941fcb0306f22df1a84a419875cd

"""Generated Roles REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.roles import CreateRole, GetRoleResponse, PatchRole, Role, RoleIdParam, RoleName


POST_ROLE = Operation(
    operation_id="postRole",
    method="POST",
    path="/v1/role",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_ROLE = Operation(
    operation_id="putRole",
    method="PUT",
    path="/v1/role",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_ROLE = Operation(
    operation_id="getRole",
    method="GET",
    path="/v1/role",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="role_name",
            name="role_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_ROLE_ID = Operation(
    operation_id="getRoleId",
    method="GET",
    path="/v1/role/{role_id}",
    parameters=(
        Parameter(
            argument_name="role_id",
            name="role_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_ROLE_ID = Operation(
    operation_id="patchRoleId",
    method="PATCH",
    path="/v1/role/{role_id}",
    parameters=(
        Parameter(
            argument_name="role_id",
            name="role_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_ROLE_ID = Operation(
    operation_id="deleteRoleId",
    method="DELETE",
    path="/v1/role/{role_id}",
    parameters=(
        Parameter(
            argument_name="role_id",
            name="role_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postRole": POST_ROLE,
    "putRole": PUT_ROLE,
    "getRole": GET_ROLE,
    "getRoleId": GET_ROLE_ID,
    "patchRoleId": PATCH_ROLE_ID,
    "deleteRoleId": DELETE_ROLE_ID,
}


class RolesAPI(ResourceAPI):
    """Generated Roles REST API."""

    def post_role(
        self,
        *,
        body: "CreateRole",
    ) -> "Role":
        return cast(
            "Role",
            self.execute(
                POST_ROLE,
                body=body,
            ),
        )

    def put_role(
        self,
        *,
        body: "CreateRole",
    ) -> "Role":
        return cast(
            "Role",
            self.execute(
                PUT_ROLE,
                body=body,
            ),
        )

    def get_role(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        role_name: "RoleName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetRoleResponse":
        return cast(
            "GetRoleResponse",
            self.execute(
                GET_ROLE,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "role_name": role_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_role_id(
        self,
        role_id: "RoleIdParam",
    ) -> "Role":
        return cast(
            "Role",
            self.execute(
                GET_ROLE_ID,
                path_parameters={"role_id": role_id},
            ),
        )

    def patch_role_id(
        self,
        role_id: "RoleIdParam",
        *,
        body: "PatchRole | None" = None,
    ) -> "Role":
        return cast(
            "Role",
            self.execute(
                PATCH_ROLE_ID,
                path_parameters={"role_id": role_id},
                body=body,
            ),
        )

    def delete_role_id(
        self,
        role_id: "RoleIdParam",
    ) -> "Role":
        return cast(
            "Role",
            self.execute(
                DELETE_ROLE_ID,
                path_parameters={"role_id": role_id},
            ),
        )
