# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 1d15b5a0fb7ad41da036560981ad6c360b21d1905a705299b05aad45fe621d6f

"""Generated ServiceTokens REST operations and resource."""

from collections.abc import Mapping

from typing import Any, cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.service_tokens import (
    CreateServiceTokenOutput,
    DeleteServiceToken,
    GetServiceTokenResponse,
    ServiceToken,
    ServiceTokenIdParam,
    ServiceTokenName,
)


POST_SERVICE_TOKEN = Operation(
    operation_id="postServiceToken",
    method="POST",
    path="/v1/service_token",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_SERVICE_TOKEN = Operation(
    operation_id="putServiceToken",
    method="PUT",
    path="/v1/service_token",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_SERVICE_TOKEN = Operation(
    operation_id="deleteServiceToken",
    method="DELETE",
    path="/v1/service_token",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_SERVICE_TOKEN = Operation(
    operation_id="getServiceToken",
    method="GET",
    path="/v1/service_token",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="service_token_name",
            name="service_token_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_SERVICE_TOKEN_ID = Operation(
    operation_id="getServiceTokenId",
    method="GET",
    path="/v1/service_token/{service_token_id}",
    parameters=(
        Parameter(
            argument_name="service_token_id",
            name="service_token_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


DELETE_SERVICE_TOKEN_ID = Operation(
    operation_id="deleteServiceTokenId",
    method="DELETE",
    path="/v1/service_token/{service_token_id}",
    parameters=(
        Parameter(
            argument_name="service_token_id",
            name="service_token_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postServiceToken": POST_SERVICE_TOKEN,
    "putServiceToken": PUT_SERVICE_TOKEN,
    "deleteServiceToken": DELETE_SERVICE_TOKEN,
    "getServiceToken": GET_SERVICE_TOKEN,
    "getServiceTokenId": GET_SERVICE_TOKEN_ID,
    "deleteServiceTokenId": DELETE_SERVICE_TOKEN_ID,
}


class ServiceTokensAPI(ResourceAPI):
    """Generated ServiceTokens REST API."""

    def post_service_token(
        self,
        *,
        body: "Mapping[str, Any]",
    ) -> "CreateServiceTokenOutput":
        return cast(
            "CreateServiceTokenOutput",
            self.execute(
                POST_SERVICE_TOKEN,
                body=body,
            ),
        )

    def put_service_token(
        self,
        *,
        body: "Mapping[str, Any]",
    ) -> "CreateServiceTokenOutput":
        return cast(
            "CreateServiceTokenOutput",
            self.execute(
                PUT_SERVICE_TOKEN,
                body=body,
            ),
        )

    def delete_service_token(
        self,
        *,
        body: "DeleteServiceToken",
    ) -> "ServiceToken":
        return cast(
            "ServiceToken",
            self.execute(
                DELETE_SERVICE_TOKEN,
                body=body,
            ),
        )

    def get_service_token(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        service_token_name: "ServiceTokenName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetServiceTokenResponse":
        return cast(
            "GetServiceTokenResponse",
            self.execute(
                GET_SERVICE_TOKEN,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "service_token_name": service_token_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_service_token_id(
        self,
        service_token_id: "ServiceTokenIdParam",
    ) -> "ServiceToken":
        return cast(
            "ServiceToken",
            self.execute(
                GET_SERVICE_TOKEN_ID,
                path_parameters={"service_token_id": service_token_id},
            ),
        )

    def delete_service_token_id(
        self,
        service_token_id: "ServiceTokenIdParam",
    ) -> "ServiceToken":
        return cast(
            "ServiceToken",
            self.execute(
                DELETE_SERVICE_TOKEN_ID,
                path_parameters={"service_token_id": service_token_id},
            ),
        )
