# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: 8d6e24ce78d8e33cbf9ba5f35d2fbc71749306d7
# OpenAPI spec SHA-256: ebac33c1422e5673f875a254b3f7a13e4d8b5f5ab9b5095fd6b48e836613d507
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 8fa3b9e035bc8fe53b347f09a2339112ad2e1efbac19ed64b8b09c59bbc24322

"""Generated SpanIframes REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.span_iframes import (
    CreateSpanIFrame,
    GetSpanIframeResponse,
    PatchSpanIFrame,
    SpanIFrame,
    SpanIframeIdParam,
    SpanIframeName,
)


POST_SPAN_IFRAME = Operation(
    operation_id="postSpanIframe",
    method="POST",
    path="/v1/span_iframe",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_SPAN_IFRAME = Operation(
    operation_id="putSpanIframe",
    method="PUT",
    path="/v1/span_iframe",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_SPAN_IFRAME = Operation(
    operation_id="getSpanIframe",
    method="GET",
    path="/v1/span_iframe",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="span_iframe_name",
            name="span_iframe_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_SPAN_IFRAME_ID = Operation(
    operation_id="getSpanIframeId",
    method="GET",
    path="/v1/span_iframe/{span_iframe_id}",
    parameters=(
        Parameter(
            argument_name="span_iframe_id",
            name="span_iframe_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_SPAN_IFRAME_ID = Operation(
    operation_id="patchSpanIframeId",
    method="PATCH",
    path="/v1/span_iframe/{span_iframe_id}",
    parameters=(
        Parameter(
            argument_name="span_iframe_id",
            name="span_iframe_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_SPAN_IFRAME_ID = Operation(
    operation_id="deleteSpanIframeId",
    method="DELETE",
    path="/v1/span_iframe/{span_iframe_id}",
    parameters=(
        Parameter(
            argument_name="span_iframe_id",
            name="span_iframe_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postSpanIframe": POST_SPAN_IFRAME,
    "putSpanIframe": PUT_SPAN_IFRAME,
    "getSpanIframe": GET_SPAN_IFRAME,
    "getSpanIframeId": GET_SPAN_IFRAME_ID,
    "patchSpanIframeId": PATCH_SPAN_IFRAME_ID,
    "deleteSpanIframeId": DELETE_SPAN_IFRAME_ID,
}


class SpanIframesAPI(ResourceAPI):
    """Generated SpanIframes REST API."""

    def post_span_iframe(
        self,
        *,
        body: "CreateSpanIFrame",
    ) -> "SpanIFrame":
        return cast(
            "SpanIFrame",
            self.execute(
                POST_SPAN_IFRAME,
                body=body,
            ),
        )

    def put_span_iframe(
        self,
        *,
        body: "CreateSpanIFrame",
    ) -> "SpanIFrame":
        return cast(
            "SpanIFrame",
            self.execute(
                PUT_SPAN_IFRAME,
                body=body,
            ),
        )

    def get_span_iframe(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        span_iframe_name: "SpanIframeName | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetSpanIframeResponse":
        return cast(
            "GetSpanIframeResponse",
            self.execute(
                GET_SPAN_IFRAME,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "span_iframe_name": span_iframe_name,
                    "org_name": org_name,
                },
            ),
        )

    def get_span_iframe_id(
        self,
        span_iframe_id: "SpanIframeIdParam",
    ) -> "SpanIFrame":
        return cast(
            "SpanIFrame",
            self.execute(
                GET_SPAN_IFRAME_ID,
                path_parameters={"span_iframe_id": span_iframe_id},
            ),
        )

    def patch_span_iframe_id(
        self,
        span_iframe_id: "SpanIframeIdParam",
        *,
        body: "PatchSpanIFrame | None" = None,
    ) -> "SpanIFrame":
        return cast(
            "SpanIFrame",
            self.execute(
                PATCH_SPAN_IFRAME_ID,
                path_parameters={"span_iframe_id": span_iframe_id},
                body=body,
            ),
        )

    def delete_span_iframe_id(
        self,
        span_iframe_id: "SpanIframeIdParam",
    ) -> "SpanIFrame":
        return cast(
            "SpanIFrame",
            self.execute(
                DELETE_SPAN_IFRAME_ID,
                path_parameters={"span_iframe_id": span_iframe_id},
            ),
        )
