# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: 404e047f847440b5fa80272a48a817a77429a4bb9bd88cf71def43fdd0f11562

"""Generated Users REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AppLimitParam, EndingBefore, Ids, OrgName, StartingAfter
from .models.users import GetUserResponse, User, UserEmail, UserFamilyName, UserGivenName, UserIdParam


GET_USER = Operation(
    operation_id="getUser",
    method="GET",
    path="/v1/user",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="given_name",
            name="given_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="family_name",
            name="family_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="email",
            name="email",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="org_name",
            name="org_name",
            location="query",
            required=False,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_USER_ID = Operation(
    operation_id="getUserId",
    method="GET",
    path="/v1/user/{user_id}",
    parameters=(
        Parameter(
            argument_name="user_id",
            name="user_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


OPERATIONS = {
    "getUser": GET_USER,
    "getUserId": GET_USER_ID,
}


class UsersAPI(ResourceAPI):
    """Generated Users REST API."""

    def get_user(
        self,
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        given_name: "UserGivenName | None" = None,
        family_name: "UserFamilyName | None" = None,
        email: "UserEmail | None" = None,
        org_name: "OrgName | None" = None,
    ) -> "GetUserResponse":
        return cast(
            "GetUserResponse",
            self.execute(
                GET_USER,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "given_name": given_name,
                    "family_name": family_name,
                    "email": email,
                    "org_name": org_name,
                },
            ),
        )

    def get_user_id(
        self,
        user_id: "UserIdParam",
    ) -> "User":
        return cast(
            "User",
            self.execute(
                GET_USER_ID,
                path_parameters={"user_id": user_id},
            ),
        )
