# Generated by scripts/generate-api-client.py. DO NOT EDIT.
# OpenAPI commit: d1f9de36c2fa4db9e8c6cf11d7321cbd53e93c6a
# OpenAPI spec SHA-256: d4fca10d8584f1613f10ccf4bb8977a0559c28b87f601bfdfacd6b9017e5bad5
# datamodel-code-generator: 0.72.4
# ruff: 0.15.21
# Generator Python: 3.14
# Content SHA-256: b3cdb3f1a5848a5fcbfe41ce2d20776a20c6b52c53d443ed9d8a69eb955757d7

"""Generated Views REST operations and resource."""

from typing import cast

from .._service import Operation, Parameter, ResourceAPI
from ..policies import RetryMode
from .models.common import AclObjectId, AclObjectType, AppLimitParam, EndingBefore, Ids, StartingAfter
from .models.views import CreateView, DeleteView, GetViewResponse, PatchView, View, ViewIdParam, ViewName, ViewType


POST_VIEW = Operation(
    operation_id="postView",
    method="POST",
    path="/v1/view",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


PUT_VIEW = Operation(
    operation_id="putView",
    method="PUT",
    path="/v1/view",
    parameters=(),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


GET_VIEW = Operation(
    operation_id="getView",
    method="GET",
    path="/v1/view",
    parameters=(
        Parameter(
            argument_name="limit",
            name="limit",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="starting_after",
            name="starting_after",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ending_before",
            name="ending_before",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="ids",
            name="ids",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="view_name",
            name="view_name",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="view_type",
            name="view_type",
            location="query",
            required=False,
        ),
        Parameter(
            argument_name="object_type",
            name="object_type",
            location="query",
            required=True,
        ),
        Parameter(
            argument_name="object_id",
            name="object_id",
            location="query",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


GET_VIEW_ID = Operation(
    operation_id="getViewId",
    method="GET",
    path="/v1/view/{view_id}",
    parameters=(
        Parameter(
            argument_name="view_id",
            name="view_id",
            location="path",
            required=True,
        ),
        Parameter(
            argument_name="object_type",
            name="object_type",
            location="query",
            required=True,
        ),
        Parameter(
            argument_name="object_id",
            name="object_id",
            location="query",
            required=True,
        ),
    ),
    has_request_body=False,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.SAFE_READ,
)


PATCH_VIEW_ID = Operation(
    operation_id="patchViewId",
    method="PATCH",
    path="/v1/view/{view_id}",
    parameters=(
        Parameter(
            argument_name="view_id",
            name="view_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


DELETE_VIEW_ID = Operation(
    operation_id="deleteViewId",
    method="DELETE",
    path="/v1/view/{view_id}",
    parameters=(
        Parameter(
            argument_name="view_id",
            name="view_id",
            location="path",
            required=True,
        ),
    ),
    has_request_body=True,
    success_statuses=(200,),
    json_success_statuses=(200,),
    retry_mode=RetryMode.NONE,
)


OPERATIONS = {
    "postView": POST_VIEW,
    "putView": PUT_VIEW,
    "getView": GET_VIEW,
    "getViewId": GET_VIEW_ID,
    "patchViewId": PATCH_VIEW_ID,
    "deleteViewId": DELETE_VIEW_ID,
}


class ViewsAPI(ResourceAPI):
    """Generated Views REST API."""

    def post_view(
        self,
        *,
        body: "CreateView",
    ) -> "View":
        return cast(
            "View",
            self.execute(
                POST_VIEW,
                body=body,
            ),
        )

    def put_view(
        self,
        *,
        body: "CreateView",
    ) -> "View":
        return cast(
            "View",
            self.execute(
                PUT_VIEW,
                body=body,
            ),
        )

    def get_view(
        self,
        object_type: "AclObjectType",
        object_id: "AclObjectId",
        *,
        limit: "AppLimitParam | None" = None,
        starting_after: "StartingAfter | None" = None,
        ending_before: "EndingBefore | None" = None,
        ids: "Ids | None" = None,
        view_name: "ViewName | None" = None,
        view_type: "ViewType | None" = None,
    ) -> "GetViewResponse":
        return cast(
            "GetViewResponse",
            self.execute(
                GET_VIEW,
                query_parameters={
                    "limit": limit,
                    "starting_after": starting_after,
                    "ending_before": ending_before,
                    "ids": ids,
                    "view_name": view_name,
                    "view_type": view_type,
                    "object_type": object_type,
                    "object_id": object_id,
                },
            ),
        )

    def get_view_id(
        self,
        view_id: "ViewIdParam",
        object_type: "AclObjectType",
        object_id: "AclObjectId",
    ) -> "View":
        return cast(
            "View",
            self.execute(
                GET_VIEW_ID,
                path_parameters={"view_id": view_id},
                query_parameters={"object_type": object_type, "object_id": object_id},
            ),
        )

    def patch_view_id(
        self,
        view_id: "ViewIdParam",
        *,
        body: "PatchView",
    ) -> "View":
        return cast(
            "View",
            self.execute(
                PATCH_VIEW_ID,
                path_parameters={"view_id": view_id},
                body=body,
            ),
        )

    def delete_view_id(
        self,
        view_id: "ViewIdParam",
        *,
        body: "DeleteView",
    ) -> "View":
        return cast(
            "View",
            self.execute(
                DELETE_VIEW_ID,
                path_parameters={"view_id": view_id},
                body=body,
            ),
        )
